"""English text catalog. Keys: ``module.type.function.summary``; ``str.format`` placeholders must match the Spanish catalog (a test checks it)."""
from __future__ import annotations

EN: dict[str, str] = {
    "advanced.cabecera.to_frame.clientes": "N customers",
    "advanced.cabecera.to_frame.id_clase": "class_id",
    "advanced.cabecera.to_frame.margen_contribucion": "Contribution margin",
    "advanced.cabecera.to_frame.margen_seguridad": "Margin of safety (%)",
    "advanced.cabecera.to_frame.margen_seguridad_unidades": "Margin of safety (units)",
    "advanced.cabecera.to_frame.medio": "Mean W",
    "advanced.cabecera.to_frame.pe_ingresos": "BEP (revenue)",
    "advanced.cabecera.to_frame.pe_unidades": "BEP (units)",
    "advanced.cabecera.to_frame.razon_mc": "CM ratio",
    "advanced.cabecera.to_frame.wq_medio": "Mean Wq",
    "advanced.cabecera.to_frame.wq_p50": "Wq p50",
    "advanced.cabecera.to_frame.wq_p90": "Wq p90",
    "advanced.cabecera.to_frame.wq_p95": "Wq p95",
    "advanced.cabecera.to_frame.wq_p99": "Wq p99",
    "advanced.clave_params.break_even_multi.fixed_cost": "fixed_cost",
    "advanced.clave_params.break_even_multi.products": "n_products",
    "advanced.clave_params.mm1_priority.clases": "N_classes",
    "advanced.clave_params.mm1_priority.residual": "R (residual)",
    "advanced.clave_params.mm1k.capacidad": "K (capacity)",
    "advanced.clave_params.mm1k.eff_tasa_efectiva": "λ_eff (effective rate)",
    "advanced.clave_params.mm1k.p0_vacio": "P0 (empty)",
    "advanced.clave_params.mm1k.pk_prob_bloqueo": "PK (blocking prob.)",
    "advanced.clave_params.monte_carlo_gg1.ca2": "ca2",
    "advanced.clave_params.monte_carlo_gg1.cs2": "cs2",
    "advanced.clave_params.monte_carlo_gg1.seed": "seed",
    "advanced.error.break_even.price_per_unit_debe_superar": "price_per_unit must exceed variable_cost_per_unit to get a positive contribution margin.",
    "advanced.error.break_even_multi.names_debe_tener_misma_longitud": "'names' must have the same length as prices.",
    "advanced.error.break_even_multi.prices_variable_costs_sales_mix": "prices, variable_costs and sales_mix must have the same length.",
    "advanced.error.break_even_multi.suma_sales_mix_debe_ser": "The sum of sales_mix must be positive.",
    "advanced.error.break_even_multi.todos_productos_deben_tener_margen": "All products must have a positive contribution margin (price > variable cost).",
    "advanced.error.break_even_sales.variable_cost_ratio_debe_estar": "'variable_cost_ratio' must be strictly between 0 and 1.",
    "advanced.error.line_balance.station_names_cycle_times_deben": "'station_names' and 'cycle_times' must have the same length.",
    "advanced.error.mm1_priority.class_names_debe_tener_misma": "'class_names' must have the same length as 'lam_list'.",
    "advanced.error.mm1_priority.lam_list_debe_contener_menos": "'lam_list' must contain at least one class.",
    "advanced.error.mm1_priority.sistema_inestable_total": "Unstable system: ρ_total = {rho_total:.4g} ≥ 1.",
    "advanced.error.mmck.capacidad_sistema_debe_ser_servidores": "'K' (system capacity) must be ≥ c (servers); got K={K}, c={c}.",
    "advanced.error.monte_carlo_gg1.sistema_inestable": "Unstable system: ρ = {rho:.4g} ≥ 1.",
    "advanced.error.queue_length_pmf.max_debe_estar_entre_recibio": "'n_max' must be between 0 and {MAX_ESTADOS}, got {n_max!r}.",
    "advanced.error.queue_length_pmf.max_debe_ser_entero_recibio": "'n_max' must be an integer >= 0, got {__name__!r}.",
    "advanced.etiqueta.summary.margen_contribucion": "Contribution margin          : {contribution_margin:.4g}",
    "advanced.etiqueta.summary.margen_seguridad_unidades": "Margin of safety              : {margin_of_safety_units:.4g} units ({margin_of_safety_pct:.2%})",
    "advanced.etiqueta.summary.mc_ponderado_promedio": "Weighted average CM                   : {weighted_avg_cm:.4g}",
    "advanced.etiqueta.summary.modelo_wq_medio_p50_p90": "Model    : {model}\nN        : {n_customers:,}\nρ        : {rho:.4f}\nMean Wq  : {Wq_mean:.6g}  (p50={Wq_p50:.4g}  p90={Wq_p90:.4g}  p95={Wq_p95:.4g}  p99={Wq_p99:.4g})\nMean W   : {W_mean:.6g}\nLq       : {Lq:.6g}\nL        : {L:.6g}",
    "advanced.etiqueta.summary.prioridad_hol_expropiativa": "M/M/1 with non-preemptive HOL priority  (μ={mu:.6g}, ρ={rho_total:.4g})",
    "advanced.etiqueta.summary.punto_equilibrio_ingresos": "Break-even point (revenue): {bep_revenue:.4g}",
    "advanced.etiqueta.summary.punto_equilibrio_ingresos_totales": "Break-even point (total revenue): {bep_revenue_total:.4g}",
    "advanced.etiqueta.summary.punto_equilibrio_unidades": "Break-even point (units): {bep_units:.4g}",
    "advanced.etiqueta.summary.punto_equilibrio_unidades_totales": "Break-even point (total units): {bep_units_total:.4g}",
    "advanced.etiqueta.summary.razon_contribucion": "Contribution ratio           : {contribution_margin_ratio:.2%}",
    "advanced.etiqueta.summary.razon_mc_ponderada": "Weighted CM ratio                     : {cm_ratio_weighted:.2%}",
    "advanced.etiqueta.summary.tiempo_takt_estaciones_minimo_teorico": "Takt time               : {takt:.6g}\nStations                : {n_stations}\nTheoretical minimum     : {theoretical_min_stations}\nBalance efficiency      : {balance_efficiency:.2%}\nBottleneck station      : {bottleneck}\n",
    "advanced.modelo.mm1k.texto": "M/M/1/{K}",
    "advanced.modelo.mmck.texto": "M/M/{c}/{K}",
    "advanced.modelo.monte_carlo_gg1.simulacion_ca2_cs2": "G/G/1 simulation (ca²={ca2:.3g}, cs²={cs2:.3g})",
    "advanced.texto_en_expresion.summary.clase": "Class",
    "advanced.texto_en_expresion.summary.cv": "CV",
    "advanced.texto_en_expresion.summary.lq": "Lq",
    "advanced.texto_en_expresion.summary.mc": "CM",
    "advanced.texto_en_expresion.summary.mezcla": "Mix",
    "advanced.texto_en_expresion.summary.pe_ingr": "BEP rev.",
    "advanced.texto_en_expresion.summary.pe_unid": "BEP units",
    "advanced.texto_en_expresion.summary.precio": "Price",
    "advanced.texto_en_expresion.summary.producto": "Product",
    "advanced.texto_en_expresion.summary.texto": "L",
    "advanced.texto_en_expresion.summary.texto_2": "W",
    "advanced.texto_en_expresion.summary.wq": "Wq",
    "advanced.valor_por_defecto.break_even_multi.producto": "Product-{expr}",
    "bottleneck.cabecera.to_frame.capacidad": "Capacity",
    "bottleneck.cabecera.to_frame.cuello_botella": "Bottleneck",
    "bottleneck.cabecera.to_frame.estacion": "Station",
    "bottleneck.cabecera.to_frame.holgura": "Slack",
    "bottleneck.cabecera.to_frame.tasa_demanda": "Demand rate",
    "bottleneck.cabecera.to_frame.utilizacion": "Utilization",
    "bottleneck.error.bottleneck_analysis.routing_fractions_debe_tener_valor": "'routing_fractions' must have one value per station.",
    "bottleneck.error.bottleneck_analysis.station_names_capacities_deben_tener": "'station_names' and 'capacities' must have the same length.",
    "bottleneck.etiqueta.summary.cb": " ← BN",
    "bottleneck.etiqueta.summary.estacion_cuello_botella": "Bottleneck station: {bottleneck}",
    "bottleneck.etiqueta.summary.tasa_demanda": "Demand rate        : {demand_rate:.6g}",
    "bottleneck.etiqueta.summary.throughput_sistema": "System throughput   : {system_throughput:.6g}",
    "bottleneck.texto_en_expresion.summary.capacidad": "Capacity",
    "bottleneck.texto_en_expresion.summary.demanda": "Demand",
    "bottleneck.texto_en_expresion.summary.estacion": "Station",
    "bottleneck.texto_en_expresion.summary.holgura": "Slack",
    "bottleneck.texto_en_expresion.summary.util": "Util.",
    "columnas.columna_df.global.ajustada": "Adjusted Q",
    "columnas.columna_df.global.articulo": "Item",
    "columnas.columna_df.global.cantidad_min": "Min. quantity",
    "columnas.columna_df.global.costo_compra": "Purchase cost",
    "columnas.columna_df.global.costo_mantener": "Holding cost",
    "columnas.columna_df.global.costo_ordenar": "Ordering cost",
    "columnas.columna_df.global.costo_preparacion": "Setup cost",
    "columnas.columna_df.global.costo_total": "Total cost",
    "columnas.columna_df.global.costo_variable": "Variable cost",
    "columnas.columna_df.global.estacion": "Station",
    "columnas.columna_df.global.factible": "Feasible",
    "columnas.columna_df.global.frecuencia_lotes": "Batch frequency",
    "columnas.columna_df.global.frecuencia_pedidos": "Order frequency",
    "columnas.columna_df.global.indice_tramo": "Break index",
    "columnas.columna_df.global.inventario_maximo": "Maximum inventory",
    "columnas.columna_df.global.inventario_promedio": "Average inventory",
    "columnas.columna_df.global.lam": "lam",
    "columnas.columna_df.global.mezcla": "Mix",
    "columnas.columna_df.global.mu": "mu",
    "columnas.columna_df.global.pe_ingresos": "BEP revenue",
    "columnas.columna_df.global.pe_unidades": "BEP units",
    "columnas.columna_df.global.precio": "Price",
    "columnas.columna_df.global.precio_unitario": "Unit price",
    "columnas.columna_df.global.producto": "Product",
    "columnas.columna_df.global.servidores": "c (servers)",
    "columnas.columna_df.global.sobrecargada": "Overloaded",
    "columnas.columna_df.global.texto": "P(N<=n)",
    "columnas.columna_df.global.texto_2": "P(N=n)",
    "columnas.columna_df.global.texto_3": "F(t)",
    "columnas.columna_df.global.texto_4": "f(t)",
    "columnas.columna_df.global.tiempo_ciclo": "Cycle_time",
    "columnas.columna_df.global.tiempo_ciclo_2": "Cycle time",
    "columnas.columna_df.global.tiempo_ocioso": "Idle_time",
    "columnas.columna_df.global.utilizacion": "Utilization",
    "fitting.cabecera.to_frame.ca2": "ca²",
    "fitting.cabecera.to_frame.cs2": "cs²",
    "fitting.error.fit_from_data.arrival_timestamps_debe_contener_menos": "'arrival_timestamps' must contain at least 2 timestamps.",
    "fitting.error.fit_from_data.arrival_timestamps_debe_ser_finito": "'arrival_timestamps' must be finite.",
    "fitting.error.fit_from_data.indique_inter_arrivals_arrival_timestamps": "Provide 'inter_arrivals' or 'arrival_timestamps', not both.",
    "fitting.error.fit_from_data.indique_menos_uno_inter_arrivals": "Provide at least one of 'inter_arrivals', 'arrival_timestamps' or 'service_times'.",
    "fitting.error.fit_times.debe_contener_menos_observaciones": "'{name}' must contain at least 2 observations.",
    "fitting.error.fit_times.todos_valores_deben_ser_finitos": "All values of '{name}' must be finite and strictly positive.",
    "fitting.etiqueta.summary.ajuste_fitresult": "Fit (FitResult)",
    "fitting.etiqueta.summary.ca2_cv2_llegadas": "  ca² (arrival CV²)       : {ca2:.6g}",
    "fitting.etiqueta.summary.cs2_cv2_servicio": "  cs² (service CV²)       : {cs2:.6g}",
    "fitting.etiqueta.summary.desv_entre_llegadas": "  interarrival std dev    : {std_ia:.6g}",
    "fitting.etiqueta.summary.desv_servicio": "  service std dev         : {std_svc:.6g}",
    "fitting.etiqueta.summary.media_entre_llegadas": "  interarrival mean       : {mean_ia:.6g}",
    "fitting.etiqueta.summary.media_servicio": "  service mean            : {mean_svc:.6g}",
    "fitting.etiqueta.summary.tasa_llegada": "  λ (arrival rate)        : {lam:.6g}  (n={n_arrivals})",
    "fitting.etiqueta.summary.tasa_servicio": "  μ (service rate)        : {mu:.6g}  (n={n_services})",
    "i18n.error.validar.idioma_no_admitido": "Unsupported language: {lang!r}. Options: {opciones}.",
    "inventory.aviso.mrp.unidades_planificadas_debieron_liberarse_antes": "{past_due:g} planned units should have been released before period 1 (lead_time={lead_time} does not fit in the horizon); see 'past_due_releases'.",
    "inventory.cabecera.modulo.articulo": "item",
    "inventory.cabecera.modulo.cantidad_pedido": "order_qty",
    "inventory.cabecera.modulo.clase": "class",
    "inventory.cabecera.modulo.clase_abc": "abc_class",
    "inventory.cabecera.modulo.clase_combinada": "combined_class",
    "inventory.cabecera.modulo.clase_xyz": "xyz_class",
    "inventory.cabecera.modulo.demanda": "demand",
    "inventory.cabecera.modulo.eoq": "Q_eoq",
    "inventory.cabecera.modulo.indice": "index",
    "inventory.cabecera.modulo.inversion": "I (investment)",
    "inventory.cabecera.modulo.inversion_2": "investment",
    "inventory.cabecera.modulo.inversion_ss": "ss_investment",
    "inventory.cabecera.modulo.nivel_servicio": "service_level",
    "inventory.cabecera.modulo.optima": "Q_optimal",
    "inventory.cabecera.modulo.pct_acumulado": "cumulative_pct",
    "inventory.cabecera.modulo.pct_valor": "value_pct",
    "inventory.cabecera.modulo.pedidos": "n_orders",
    "inventory.cabecera.modulo.pedidos_ano": "N (orders/year)",
    "inventory.cabecera.modulo.periodo": "period",
    "inventory.cabecera.modulo.periodos_cubiertos": "periods_covered",
    "inventory.cabecera.modulo.posicion": "position",
    "inventory.cabecera.modulo.punto_reorden": "reorder_point",
    "inventory.cabecera.modulo.sigma_dlt": "sigma_dlt",
    "inventory.cabecera.modulo.stock_seguridad": "safety_stock",
    "inventory.cabecera.modulo.valor_anual": "annual_value",
    "inventory.cabecera.modulo.valor_unitario": "unit_value",
    "inventory.cabecera.to_frame.costo_mantener": "Holding cost",
    "inventory.cabecera.to_frame.costo_ordenar": "Ordering cost",
    "inventory.cabecera.to_frame.costo_preparacion": "Setup cost",
    "inventory.cabecera.to_frame.costo_total": "Total cost",
    "inventory.cabecera.to_frame.demanda_media_lt": "Mean demand over LT",
    "inventory.cabecera.to_frame.desv_demanda_lt": "Demand std dev over LT",
    "inventory.cabecera.to_frame.exist_proy": "Proj_on_hand",
    "inventory.cabecera.to_frame.faltante_esperado": "Expected shortage",
    "inventory.cabecera.to_frame.frecuencia_lotes": "Batch frequency",
    "inventory.cabecera.to_frame.frecuencia_pedidos": "Order frequency",
    "inventory.cabecera.to_frame.inventario_maximo": "Maximum inventory",
    "inventory.cabecera.to_frame.inventario_promedio": "Average inventory",
    "inventory.cabecera.to_frame.lib_plan": "Planned_release",
    "inventory.cabecera.to_frame.nivel_servicio": "Service level",
    "inventory.cabecera.to_frame.periodo": "Period",
    "inventory.cabecera.to_frame.punto_reorden": "Reorder point",
    "inventory.cabecera.to_frame.razon_critica": "Critical ratio",
    "inventory.cabecera.to_frame.recep_plan": "Planned_receipt",
    "inventory.cabecera.to_frame.recep_prog": "Sched_receipt",
    "inventory.cabecera.to_frame.req_bruto": "Gross_req",
    "inventory.cabecera.to_frame.req_neto": "Net_req",
    "inventory.cabecera.to_frame.sobrante_esperado": "Expected leftover",
    "inventory.cabecera.to_frame.stock_seguridad": "Safety stock",
    "inventory.cabecera.to_frame.tiempo_ciclo": "Cycle time",
    "inventory.cabecera.to_frame.utilidad_esperada": "Expected profit",
    "inventory.cabecera.to_frame.ventas_esperadas": "Expected sales",
    "inventory.clave_params.ebq.production_rate": "production_rate",
    "inventory.clave_params.ebq.setup_cost": "setup_cost",
    "inventory.clave_params.eoq.demand_rate": "demand_rate",
    "inventory.clave_params.eoq.holding_cost": "holding_cost",
    "inventory.clave_params.eoq.ordering_cost": "ordering_cost",
    "inventory.clave_params.eoq_multi.items": "n_items",
    "inventory.clave_params.eoq_quantity_discount.holding_cost_rate": "holding_cost_rate",
    "inventory.clave_params.newsvendor.cost": "cost",
    "inventory.clave_params.newsvendor.demand_mean": "demand_mean",
    "inventory.clave_params.newsvendor.price": "price",
    "inventory.clave_params.newsvendor.salvage": "salvage",
    "inventory.clave_params.reorder_point.demand_std": "demand_std",
    "inventory.clave_params.reorder_point.lead_time": "lead_time",
    "inventory.clave_params.reorder_point.lead_time_std": "lead_time_std",
    "inventory.clave_params.rs_policy.review_period": "review_period",
    "inventory.error.abc_analysis.debe_cumplirse_threshold_threshold": "0 < a_threshold < b_threshold < 1 must hold.",
    "inventory.error.abc_analysis.valor_anual_total_cero_todas": "The total annual value is zero (all demands are 0): there is nothing to classify.",
    "inventory.error.clave.falta_clave": "{nombre}[{i}]: missing key '{clave}'.",
    "inventory.error.ebq.production_rate_debe_superar_demand": "production_rate ({P}) must exceed demand_rate ({D}).",
    "inventory.error.eoq_lagrangian_bisect.restriccion_puede_satisfacer_ninguna_cantidad": "The constraint cannot be satisfied with any positive order quantity.",
    "inventory.error.eoq_multi.todas_secuencias_entrada_deben_tener": "All input sequences must have the same length.",
    "inventory.error.eoq_multi_constrained.budget_unit_costs_debe_tener": "'budget_unit_costs' must have the same length as demand_rates.",
    "inventory.error.eoq_multi_constrained.budget_unit_costs_obligatorio_cuando": "'budget_unit_costs' is required when 'budget' is given.",
    "inventory.error.eoq_multi_constrained.constraints_debe_ser_diccionario_name": "constraints[{j}] must be a dictionary with 'name', 'weights' and 'bound'.",
    "inventory.error.eoq_multi_constrained.restriccion_weights_tiene_longitud_distinta": "Constraint '{expr}': 'weights' has a different length than demand_rates.",
    "inventory.error.eoq_multi_constrained.space_per_unit_debe_tener": "'space_per_unit' must have the same length as demand_rates.",
    "inventory.error.eoq_multi_constrained.space_per_unit_obligatorio_cuando": "'space_per_unit' is required when 'space' is given.",
    "inventory.error.eoq_quantity_discount.feasible_price_break_found": "No feasible price break found.",
    "inventory.error.eoq_quantity_discount.price_breaks_debe_contener_menos": "price_breaks must contain at least one entry.",
    "inventory.error.exchange_curve.indique_como_maximo_uno_target": "Provide at most one of 'target_orders' or 'target_investment'.",
    "inventory.error.exchange_curve.items_debe_contener_menos_elemento": "'items' must contain at least one element.",
    "inventory.error.exchange_curve.items_unit_value_debe_ser": "items[{idx}]['unit_value'] must be > 0.",
    "inventory.error.leer_items.debe_contener_menos_elemento": "'{nombre}' must contain at least one element.",
    "inventory.error.leer_items.debe_ser_diccionario_recibio": "{nombre}[{i}] must be a dictionary, got {__name__!r}.",
    "inventory.error.leer_items.debe_ser_lista_diccionarios_recibio": "'{nombre}' must be a list of dictionaries, got {__name__!r}.",
    "inventory.error.mrp.lead_time_debe_ser_entero": "'lead_time' must be a non-negative integer.",
    "inventory.error.mrp.lot_size_debe_ser_lfl": "'lot_size' must be 'LFL' or a positive number.",
    "inventory.error.mrp.periods_debe_tener_misma_longitud": "'periods' must have the same length as 'gross_requirements'.",
    "inventory.error.mrp.scheduled_receipts_debe_tener_misma": "'scheduled_receipts' must have the same length as 'gross_requirements'.",
    "inventory.error.newsvendor.cost_debe_ser_menor_price": "'cost' must be less than 'price' (otherwise Cu ≤ 0).",
    "inventory.error.newsvendor.salvage_debe_ser_menor_cost": "'salvage' must be less than 'cost' (otherwise Co ≤ 0).",
    "inventory.error.reorder_point.service_level_debe_estar_estrictamente": "'service_level' must be strictly between 0 and 1.",
    "inventory.error.safety_stock_curve.indique_como_maximo_uno_target": "Provide at most one of 'target_service_level' or 'target_ss_investment'.",
    "inventory.error.safety_stock_curve.items_lead_time_std_debe": "items[{idx}]['lead_time_std'] must be ≥ 0.",
    "inventory.error.safety_stock_curve.target_service_level_debe_estar": "'target_service_level' must be strictly between 0 and 1.",
    "inventory.error.safety_stock_curve.todos_articulos_tienen_demand_std": "All items have demand_std=0: the safety stock is always 0.",
    "inventory.error.xyz_analysis.debe_cumplirse_threshold_threshold": "0 ≤ x_threshold < y_threshold must hold.",
    "inventory.error.xyz_analysis.items_falta_cv_demand_std": "items[{i}]: missing 'cv' or ('demand_std' and 'demand_mean'/'demand_rate').",
    "inventory.etiqueta.exchange_curve.eoq": "eoq",
    "inventory.etiqueta.exchange_curve.inversion": "investment={ti:.4g}",
    "inventory.etiqueta.exchange_curve.pedidos": "orders={to:.4g}",
    "inventory.etiqueta.safety_stock_curve.base": "base (z=0)",
    "inventory.etiqueta.safety_stock_curve.inversion_ss": "ss_investment={ti:.4g}",
    "inventory.etiqueta.safety_stock_curve.nivel_servicio": "service_level={sl_val:.4%}",
    "inventory.etiqueta.summary.abc_xyz_total": "ABC\\XYZ   X     Y     Z   Total",
    "inventory.etiqueta.summary.articulo": "Item: {item_name}",
    "inventory.etiqueta.summary.cantidad_optima_unidades_precio_unitario": "Optimal quantity   : {optimal_qty:.4g} units\nUnit price         : {unit_price:.4g}\nTotal cost/year    : {total_cost:.6g}\n  Purchase cost    : {purchase_cost:.6g}\n  Ordering cost    : {ordering_cost_total:.6g}\n  Holding cost     : {holding_cost_total:.6g}",
    "inventory.etiqueta.summary.cantidad_optima_unidades_razon_critica": "Optimal quantity       : {optimal_qty:.4g} units\nCritical ratio         : {critical_ratio:.4g}\nExpected profit        : {expected_profit:.6g}\nExpected sales         : {expected_sales:.4g}\nExpected leftover      : {expected_leftover:.4g}\nExpected shortage      : {expected_stockout:.4g}\nUnderage cost Cu       : {underage_cost:.4g}\nOverage cost Co        : {overage_cost:.4g}",
    "inventory.etiqueta.summary.costo_mantener": "  Holding cost       : {total_holding_cost:.6g}",
    "inventory.etiqueta.summary.costo_preparacion": "  Setup cost         : {total_setup_cost:.6g}",
    "inventory.etiqueta.summary.costo_total": "Total cost           : {total_cost:.6g}",
    "inventory.etiqueta.summary.costo_total_2": "\nTotal cost: {total_cost:.6g}",
    "inventory.etiqueta.summary.costo_total_restricciones": "Total cost (constrained)  : {total_cost:.6g}",
    "inventory.etiqueta.summary.costo_total_sin_restricciones": "Total cost (unconstrained): {unconstrained_total_cost:.6g}",
    "inventory.etiqueta.summary.ct": "  {expr:<16} Q*={expr2:.4g}  TC={expr3:.4g}",
    "inventory.etiqueta.summary.cv": "CV > {expr:.2g}",
    "inventory.etiqueta.summary.cv_2": "CV ≤ {expr:.2g}",
    "inventory.etiqueta.summary.cv_3": "{expr:.2g} < CV ≤ {expr2:.2g}",
    "inventory.etiqueta.summary.ebq_tamano_lote_unidades_inventario": "EBQ (batch size)   : {ebq:.4g} units\nMaximum inventory  : {max_inventory:.4g}\nAverage inventory  : {avg_inventory:.4g}\nBatch frequency    : {order_frequency:.4g} batches/period\nCycle time         : {cycle_time:.4g} periods\nProduction time    : {production_time:.4g} periods\nTotal cost         : {total_cost:.6g}\n  Holding cost     : {holding_cost_total:.6g}\n  Setup cost       : {setup_cost_total:.6g}",
    "inventory.etiqueta.summary.eoq_cantidad_pedido_unidades_frecuencia": "EOQ (order quantity): {eoq:.4g} units\nOrder frequency     : {order_frequency:.4g} orders/period\nCycle time          : {cycle_time:.4g} periods\nTotal cost          : {total_cost:.6g}\n  Holding cost      : {holding_cost_total:.6g}\n  Ordering cost     : {ordering_cost_total:.6g}",
    "inventory.etiqueta.summary.inversion_eoq": "Investment (EOQ)        : {investment_eoq:.4g}",
    "inventory.etiqueta.summary.inversion_optimo": "Investment (optimal)    : {investment_optimal:.4g}",
    "inventory.etiqueta.summary.inversion_ss": "SS investment     : {ss_investment:.4g}",
    "inventory.etiqueta.summary.metodo": "Method                : {method}",
    "inventory.etiqueta.summary.multiplicador": "Multiplier k            : {multiplier:.4f}",
    "inventory.etiqueta.summary.nivel_servicio": "Service level     : {service_level:.4%}",
    "inventory.etiqueta.summary.numero_pedidos": "Number of orders     : {n_orders}",
    "inventory.etiqueta.summary.objetivo": "Target                  : {target}",
    "inventory.etiqueta.summary.objetivo_2": "Target            : {target}",
    "inventory.etiqueta.summary.pedidos_ano_eoq": "Orders/year (EOQ)       : {n_orders_eoq:.4g}",
    "inventory.etiqueta.summary.pedidos_ano_optimo": "Orders/year (optimal)   : {n_orders_optimal:.4g}",
    "inventory.etiqueta.summary.politica_revision_continua_cantidad_pedido": "(r, Q) continuous-review policy\n  Order quantity Q*   : {order_qty:.4g}\n  Reorder point r     : {reorder_point:.4g}\n  Safety stock SS     : {safety_stock:.4g}\n  Service level       : {service_level:.2%}\n  Average inventory   : {avg_inventory:.4g}\n  Total cost          : {total_cost:.6g}",
    "inventory.etiqueta.summary.politica_revision_periodica_periodo_revision": "(R, S) periodic-review policy\n  Review period R     : {review_period:.4g}\n  Order-up-to level S : {order_up_to:.4g}\n  Safety stock SS     : {safety_stock:.4g}\n  Service level       : {service_level:.2%}\n  Average inventory   : {avg_inventory:.4g}\n  Total cost          : {total_cost:.6g}",
    "inventory.etiqueta.summary.punto_reorden_unidades_stock_seguridad": "Reorder point       : {reorder_point:.4g} units\nSafety stock        : {safety_stock:.4g} units\nService level       : {service_level:.2%}\nz                   : {z_score:.4g}\nMean demand over LT : {mean_demand_lt:.4g}\nDemand std over LT  : {std_demand_lt:.4g}",
    "inventory.etiqueta.summary.restricciones_activas": "Binding constraints: {expr}",
    "inventory.etiqueta.summary.texto": "A",
    "inventory.etiqueta.summary.texto_2": "B",
    "inventory.etiqueta.summary.texto_3": "C",
    "inventory.etiqueta.summary.texto_4": "z                 : {z:.4f}",
    "inventory.etiqueta.summary.texto_5": "X",
    "inventory.etiqueta.summary.texto_6": "Y",
    "inventory.etiqueta.summary.texto_7": "Z",
    "inventory.etiqueta.summary.total": "Total  ",
    "inventory.etiqueta.summary.valor_anual_total": "Total annual value : {total_value:.6g}",
    "inventory.modelo.lot_for_lot.lote_lote": "Lot-for-lot",
    "inventory.modelo.silver_meal.silver_meal": "Silver-Meal",
    "inventory.modelo.wagner_whitin.wagner_whitin": "Wagner-Whitin",
    "inventory.texto_en_expresion.summary.artic": "%Items",
    "inventory.texto_en_expresion.summary.artic_2": "Items",
    "inventory.texto_en_expresion.summary.cantidad": "Quantity",
    "inventory.texto_en_expresion.summary.clase": "Class",
    "inventory.texto_en_expresion.summary.cubre": "Covers",
    "inventory.texto_en_expresion.summary.ep": "POH",
    "inventory.texto_en_expresion.summary.lpl": "PRel",
    "inventory.texto_en_expresion.summary.ninguna": "none",
    "inventory.texto_en_expresion.summary.periodo": "Period",
    "inventory.texto_en_expresion.summary.rango_cv": "CV range",
    "inventory.texto_en_expresion.summary.rb": "GR",
    "inventory.texto_en_expresion.summary.rn": "NR",
    "inventory.texto_en_expresion.summary.rp": "SR",
    "inventory.texto_en_expresion.summary.rpl": "PR",
    "inventory.texto_en_expresion.summary.valor": "%Value",
    "inventory.valor_por_defecto.abc_analysis.articulo": "Item{expr}",
    "inventory.valor_por_defecto.eoq_multi.articulo": "Item-{expr}",
    "inventory.valor_por_defecto.exchange_curve.texto": "I{expr}",
    "inventory.valor_por_defecto.mrp.articulo": "Item",
    "kpi.cabecera.to_frame.formula": "formula",
    "kpi.cabecera.to_frame.nivel": "level",
    "kpi.cabecera.to_frame.nombre": "name",
    "kpi.cabecera.to_frame.unidad": "unit",
    "kpi.cabecera.to_frame.valor": "value",
    "kpi.kpi.oee_kpi_tree.calidad": "Quality",
    "kpi.kpi.oee_kpi_tree.ciclo_ideal_ciclo_real": "Ideal cycle / Actual cycle",
    "kpi.kpi.oee_kpi_tree.disponibilidad": "Availability",
    "kpi.kpi.oee_kpi_tree.oee": "OEE",
    "kpi.kpi.oee_kpi_tree.planificado_paradas_planificado": "(Planned − Stops) / Planned",
    "kpi.kpi.oee_kpi_tree.rendimiento": "Performance",
    "kpi.kpi.oee_kpi_tree.texto": "A × P × Q",
    "kpi.kpi.oee_kpi_tree.unidades_buenas_unidades_totales": "Good units / Total units",
    "kpi.kpi.roi_kpi_tree.costo_fijo": "Fixed cost",
    "kpi.kpi.roi_kpi_tree.costo_fijo_costo_variable": "Fixed cost + Variable cost",
    "kpi.kpi.roi_kpi_tree.costo_total": "Total cost",
    "kpi.kpi.roi_kpi_tree.costo_unidad": "Cost / unit",
    "kpi.kpi.roi_kpi_tree.costo_unidad_unidades_vendidas": "Cost/unit × Units sold",
    "kpi.kpi.roi_kpi_tree.costo_variable": "Variable cost",
    "kpi.kpi.roi_kpi_tree.ingresos": "Revenue",
    "kpi.kpi.roi_kpi_tree.ingresos_costo_total": "Revenue − Total cost",
    "kpi.kpi.roi_kpi_tree.inversion": "Investment",
    "kpi.kpi.roi_kpi_tree.roi": "ROI",
    "kpi.kpi.roi_kpi_tree.unidad": "{currency}/unit",
    "kpi.kpi.roi_kpi_tree.unidades": "units",
    "kpi.kpi.roi_kpi_tree.unidades_vendidas": "Units sold",
    "kpi.kpi.roi_kpi_tree.utilidad_neta": "Net profit",
    "kpi.kpi.roi_kpi_tree.utilidad_neta_inversion": "Net profit / Investment",
    "kpi.kpi.throughput_kpi_tree.capacidad": "Capacity",
    "kpi.kpi.throughput_kpi_tree.real_capacidad": "Actual / Capacity",
    "kpi.kpi.throughput_kpi_tree.real_tasa_defectos": "Actual × (1 − Defect rate)",
    "kpi.kpi.throughput_kpi_tree.tasa_buenos": "Good rate",
    "kpi.kpi.throughput_kpi_tree.tasa_defectos": "1 − Defect rate",
    "kpi.kpi.throughput_kpi_tree.throughput_efectivo": "Effective throughput",
    "kpi.kpi.throughput_kpi_tree.throughput_real": "Actual throughput",
    "kpi.kpi.throughput_kpi_tree.unidades": "units/{time_unit}",
    "kpi.kpi.throughput_kpi_tree.utilizacion": "Utilization",
    "main.cli.add_lam_mu.tasa_llegadas": "Arrival rate λ",
    "main.cli.add_lam_mu.tasa_servicio_servidor": "Service rate μ per server",
    "main.cli.main.aproximacion_kingman": "Kingman approximation for G/G/1",
    "main.cli.main.cantidad_economica_pedido_eoq": "Economic order quantity (EOQ)",
    "main.cli.main.cola_servicio_deterministico": "M/D/1 queue with deterministic service",
    "main.cli.main.cola_servidor": "M/M/1 single-server queue",
    "main.cli.main.cola_varios_servidores": "M/M/c multi-server queue",
    "main.cli.main.costo_fijo_pedido": "Fixed cost per order",
    "main.cli.main.costo_mantener_unidad_periodo": "Holding cost per unit per period",
    "main.cli.main.cv2_tiempos_entre_llegadas": "CV² of the interarrival times",
    "main.cli.main.cv2_tiempos_servicio": "CV² of the service times",
    "main.cli.main.error": "Error: {exc}",
    "main.cli.main.herramientas_teoria_colas_investigacion_operaciones": "Queueing theory and operations research tools.",
    "main.cli.main.modelo": "MODEL",
    "main.cli.main.numero_servidores": "Number of servers",
    "main.cli.main.resuelve_ley_little_variable_faltante": "Solves Little's law for the missing variable",
    "main.cli.main.tasa_demanda_unidades_periodo": "Demand rate (units/period)",
    "main.cli.main.walopy": "walopy {__version__}",
    "network.cabecera.to_frame.estacion": "Station",
    "network.cabecera.to_frame.ext": "λ_ext",
    "network.cabecera.to_frame.total": "λ_total",
    "network.clave_params.jackson_network.texto": "J",
    "network.clave_params.jackson_network.total_gamma": "total_gamma",
    "network.error.jackson_network.estacion_inestable_aumente_capacidad_reduzca": "Station '{expr}' is unstable: ρ = {rho_j:.4g} ≥ 1. Increase the capacity or reduce the arrival rates.",
    "network.error.jackson_network.filas_matriz_ruteo_deben_sumar": "The rows of the routing matrix must sum to ≤ 1.",
    "network.error.jackson_network.mu_gamma_station_names_deben": "'mu', 'gamma' and 'station_names' must have the same length.",
    "network.error.jackson_network.routing_debe_ser_matriz_recibio": "'routing' must be a ({J}×{J2}) matrix, got shape {shape}.",
    "network.error.jackson_network.servers_debe_tener_misma_longitud": "'servers' must have the same length as 'station_names'.",
    "network.error.jackson_network.tasas_llegada_efectivas_negativas_revise": "Negative effective arrival rates: check the routing matrix (closed loops?).",
    "network.error.jackson_network.todas_probabilidades_ruteo_deben_ser": "All routing probabilities must be ≥ 0.",
    "network.etiqueta.summary.sistema_clientes_totales_red": "L_system  : {L_system:.6g}  (total customers in the network)",
    "network.etiqueta.summary.sistema_tiempo_medio_permanencia_red": "W_system  : {W_system:.6g}  (mean time in the network)",
    "network.texto_en_expresion.summary.estacion": "Station",
    "network.texto_en_expresion.summary.ext": "λ_ext",
    "network.texto_en_expresion.summary.lq": "Lq",
    "network.texto_en_expresion.summary.texto": "L",
    "network.texto_en_expresion.summary.texto_2": "W",
    "network.texto_en_expresion.summary.tot": "λ_tot",
    "network.texto_en_expresion.summary.wq": "Wq",
    "operations.cabecera.to_frame.calidad": "Quality (Q)",
    "operations.cabecera.to_frame.capacidad": "Capacity",
    "operations.cabecera.to_frame.costo_fijo_unidad": "Fixed cost / unit",
    "operations.cabecera.to_frame.costo_total": "Total cost",
    "operations.cabecera.to_frame.costo_unitario_total": "Total unit cost",
    "operations.cabecera.to_frame.costo_variable_unidad": "Variable cost / unit",
    "operations.cabecera.to_frame.disponibilidad": "Availability (A)",
    "operations.cabecera.to_frame.eficiencia": "Efficiency",
    "operations.cabecera.to_frame.rendimiento": "Performance (P)",
    "operations.cabecera.to_frame.throughput": "Throughput",
    "operations.cabecera.to_frame.unidades_producidas": "Units produced",
    "operations.cabecera.to_frame.utilizacion": "Utilization",
    "operations.etiqueta.summary.calidad": "Quality      (Q)   : {quality:.2%}",
    "operations.etiqueta.summary.disponibilidad": "Availability (A)   : {availability:.2%}",
    "operations.etiqueta.summary.oee": "OEE                : {oee:.2%}",
    "operations.etiqueta.summary.rendimiento": "Performance  (P)   : {performance:.2%}",
    "operations.etiqueta.summary.unidades_producidas_costo_fijo_unidad": "Units produced         : {units_produced:.6g}\nFixed cost / unit      : {fixed_cost_per_unit:.6g}\nVariable cost / unit   : {variable_cost_per_unit:.6g}\nTotal unit cost        : {unit_cost:.6g}\nTotal cost             : {total_cost:.6g}",
    "operations.etiqueta.summary.utilizacion_eficiencia_throughput_capacidad": "Utilization : {utilization:.2%}\nEfficiency  : {efficiency:.2%}\nThroughput  : {throughput:.6g}\nCapacity    : {capacity:.6g}",
    "plotting.grafica.collect.br": "<b>{name}</b><br>{value:.6g}{unit_str}{formula_str}",
    "plotting.grafica.collect.br_2": "<br><i>{formula}</i>",
    "plotting.grafica.plot_bottleneck.cuello_botella": "Bottleneck: {bottleneck}",
    "plotting.grafica.plot_bottleneck.limite_capacidad": "Capacity limit",
    "plotting.grafica.plot_bottleneck.utilizacion": "Utilization",
    "plotting.grafica.plot_break_even.analisis_punto_equilibrio": "Break-even analysis",
    "plotting.grafica.plot_break_even.ingresos": "Revenue",
    "plotting.grafica.plot_break_even.monto": "Amount",
    "plotting.grafica.plot_break_even.pe": "BEP ({bep:.0f} {expr})",
    "plotting.grafica.plot_break_even.punto_equilibrio": "Break-even point",
    "plotting.grafica.plot_break_even.real": "Actual ({actual:.0f})",
    "plotting.grafica.plot_break_even.unidades": "Units",
    "plotting.grafica.plot_break_even.ventas": "Sales",
    "plotting.grafica.plot_break_even.zona_utilidad": "Profit zone",
    "plotting.grafica.plot_eoq.cantidad_pedido": "Order quantity Q",
    "plotting.grafica.plot_eoq.costo_mantener_hq": "Holding cost (hQ/2)",
    "plotting.grafica.plot_eoq.costo_ordenar_kd": "Ordering cost (KD/Q)",
    "plotting.grafica.plot_eoq.eoq": "EOQ = {Q_star:.4g}",
    "plotting.grafica.plot_eoq.eoq_curvas_costo": "EOQ — Cost curves",
    "plotting.grafica.plot_kpi_tree.arbol_kpi": "KPI tree — {name}",
    "plotting.grafica.plot_kpi_tree.customdata_extra_extra": "%{{customdata}}<extra></extra>",
    "plotting.grafica.plot_line_balance.balance_linea_efic": "Line balance — eff. {balance_efficiency:.1%}",
    "plotting.grafica.plot_line_balance.estacion": "Station",
    "plotting.grafica.plot_line_balance.takt": "Takt = {takt:.4g}",
    "plotting.grafica.plot_line_balance.tiempo": "Time",
    "plotting.grafica.plot_line_balance.tiempo_ciclo": "Cycle time",
    "plotting.grafica.plot_line_balance.tiempo_ocioso": "Idle time",
    "plotting.grafica.plot_oee.calidad": "Quality",
    "plotting.grafica.plot_oee.clase_mundial_85": "World class (85%)",
    "plotting.grafica.plot_oee.descomposicion_oee": "OEE breakdown",
    "plotting.grafica.plot_oee.disponibilidad": "Availability",
    "plotting.grafica.plot_oee.rendimiento": "Performance",
    "plotting.grafica.plot_oee.valor_factor": "Factor value",
    "plotting.grafica.plot_optimize_servers.costo_espera": "Waiting cost",
    "plotting.grafica.plot_optimize_servers.costo_servidores": "Server cost",
    "plotting.grafica.plot_optimize_servers.costo_total": "Total cost",
    "plotting.grafica.plot_optimize_servers.costo_unidad_tiempo": "Cost per unit of time",
    "plotting.grafica.plot_optimize_servers.numero_servidores": "Number of servers (c)",
    "plotting.grafica.plot_optimize_servers.optimizacion_costo_servidores": "Server cost optimization",
    "plotting.grafica.plot_optimize_servers.optimo": "optimal c = {optimal_servers}",
    "plotting.grafica.plot_queue_distribution.clientes": "n (customers)",
    "plotting.grafica.plot_queue_distribution.distribuciones": "M/M/1 distributions",
    "plotting.grafica.plot_queue_distribution.fda_tiempo_permanencia": "F(t) — CDF of the time in the system",
    "plotting.grafica.plot_queue_distribution.longitud_cola": "P(N = n) — Queue length",
    "plotting.grafica.plot_queue_distribution.nn": "P(N≤n)",
    "plotting.grafica.plot_queue_distribution.probabilidad": "Probability",
    "plotting.grafica.plot_queue_distribution.texto": "F(t)",
    "plotting.grafica.plot_queue_distribution.texto_2": "F(t) / f(t)",
    "plotting.grafica.plot_queue_distribution.texto_3": "P(N=n)",
    "plotting.grafica.plot_queue_distribution.texto_4": "f(t)",
    "plotting.grafica.plot_queue_distribution.tiempo": "t (time)",
    "plotting.grafica.plot_queue_metrics.resumen_kpi": "{model} — KPI summary",
    "plotting.grafica.plot_queue_metrics.valor": "Value",
    "plotting.grafica.plot_queue_sensitivity.curva": "{label} curve",
    "plotting.grafica.plot_queue_sensitivity.lq_longitud_media_cola": "Lq (mean queue length)",
    "plotting.grafica.plot_queue_sensitivity.sensibilidad_cola": "{model} — Queue sensitivity",
    "plotting.grafica.plot_queue_sensitivity.utilizacion": "Utilization ρ",
    "plotting.grafica.plot_queue_sensitivity.wq_espera_media_cola": "Wq (mean wait in queue)",
    "plotting.grafica.plot_sensitivity.sensibilidad": "Sensitivity: {param}",
    "plotting.grafica.plot_simulation.distribucion_wq": "Wq distribution",
    "plotting.grafica.plot_simulation.fda_empirica": "Empirical CDF",
    "plotting.grafica.plot_simulation.fda_wq": "CDF of Wq",
    "plotting.grafica.plot_simulation.frecuencia": "Frequency",
    "plotting.grafica.plot_simulation.probabilidad_acumulada": "Cumulative probability",
    "plotting.grafica.plot_simulation.wq": "Wq",
    "plotting.grafica.plot_simulation.wq_tiempo_espera": "Wq (waiting time)",
    "plotting.texto_en_expresion.plot_break_even.unidades": "units",
    "plotting.texto_en_expresion.plot_break_even.ventas": "sales",
    "project.cabecera.to_frame.actividad": "Activity",
    "project.cabecera.to_frame.critica": "Critical",
    "project.cabecera.to_frame.duracion": "Duration",
    "project.cabecera.to_frame.hl": "FF",
    "project.cabecera.to_frame.ht": "TF",
    "project.cabecera.to_frame.predecesoras": "Predecessors",
    "project.error.cpm.actividad_falta_clave_duration": "Activity '{nm}': missing key 'duration'.",
    "project.error.leer_actividades.activities_debe_contener_menos_actividad": "'activities' must contain at least one activity.",
    "project.error.leer_actividades.activities_debe_ser_diccionario_recibio": "activities[{i}] must be a dictionary, got {__name__!r}.",
    "project.error.leer_actividades.activities_debe_ser_lista_diccionarios": "'activities' must be a list of dictionaries.",
    "project.error.leer_actividades.activities_falta_clave_name": "activities[{i}]: missing key 'name'.",
    "project.error.leer_actividades.activities_predecessors_debe_ser_lista": "activities[{i}]['predecessors'] must be a list of names.",
    "project.error.leer_actividades.nombre_actividad_duplicado_cada_actividad": "Duplicate activity name: '{nm}'. Each activity must have a unique name.",
    "project.error.pert.actividad_falta_clave": "Activity '{nm}': missing key '{clave}'.",
    "project.error.pert.actividad_requiere_optimistic_most_likely": "Activity '{nm}': optimistic ≤ most_likely ≤ pessimistic is required.",
    "project.error.probability.probability_requiere_resultado_pert_varianza": "probability() requires a PERT result with nonzero variance.",
    "project.error.toposort_and_succ.actividad_referencia_predecesor_desconocido": "Activity '{name}' references an unknown predecessor '{pred}'.",
    "project.error.toposort_and_succ.actividades_contienen_ciclo": "The activities contain a cycle.",
    "project.etiqueta.summary.duracion_proyecto": "Project duration   : {project_duration:.4g}",
    "project.etiqueta.summary.metodo": "Method             : {method}",
    "project.etiqueta.summary.proyecto": "Project σ          : {project_std:.4g}",
    "project.etiqueta.summary.ruta_critica": "Critical path      : {expr}",
    "project.etiqueta.summary.varianza_proyecto": "Project variance   : {project_variance:.4g}",
    "queuing.cabecera.to_frame.lq_cola": "Lq (in queue)",
    "queuing.cabecera.to_frame.servidores": "c (servers)",
    "queuing.cabecera.to_frame.sistema": "L (in the system)",
    "queuing.cabecera.to_frame.tasa_llegada": "λ (arrival rate)",
    "queuing.cabecera.to_frame.tasa_servicio": "μ (service rate)",
    "queuing.cabecera.to_frame.tiempo_sistema": "W (time in the system)",
    "queuing.cabecera.to_frame.utilizacion": "ρ (utilization)",
    "queuing.cabecera.to_frame.wq_tiempo_espera": "Wq (waiting time)",
    "queuing.clave_params.kingman.ca2_cv2_llegadas": "ca² (arrival CV²)",
    "queuing.clave_params.kingman.cs2_cv2_servicio": "cs² (service CV²)",
    "queuing.clave_params.mm1.p0_prob_sistema_vacio": "P0 (empty-system prob.)",
    "queuing.clave_params.mmc.erlang": "C(c,a) Erlang-C",
    "queuing.error.cv2_triangular.media_distribucion_cv2_esta_definido": "The mean of the distribution is 0: CV² is not defined.",
    "queuing.error.cv2_triangular.triangular_requiere": "The triangular distribution requires a ≤ m ≤ b.",
    "queuing.error.cv2_uniform.uniforme_requiere": "The uniform distribution requires b > a.",
    "queuing.error.littles_law.exactamente_lam_debe_ser_none": "Exactly one of L, lam, W must be None.",
    "queuing.error.md1.sistema_inestable": "Unstable system: ρ = {rho:.4g} ≥ 1.",
    "queuing.error.mm1.sistema_inestable_requiere": "Unstable system: ρ = {rho:.4g} ≥ 1. Requires λ < μ.",
    "queuing.error.mmc.sistema_inestable_requiere": "Unstable system: ρ = {rho:.4g} ≥ 1. Requires λ < c·μ.",
    "queuing.etiqueta.summary.lq_unidades_promedio_cola": "Lq     : {Lq:.6g}  (average units in queue)",
    "queuing.etiqueta.summary.modelo": "Model  : {model}",
    "queuing.etiqueta.summary.servidores": "c      : {servers}  (servers)",
    "queuing.etiqueta.summary.tasa_llegada": "λ      : {lam:.6g}  (arrival rate)",
    "queuing.etiqueta.summary.tasa_servicio_servidor": "μ      : {mu:.6g}  (service rate per server)",
    "queuing.etiqueta.summary.tiempo_promedio_sistema": "W      : {W:.6g}  (average time in the system)",
    "queuing.etiqueta.summary.unidades_promedio_sistema": "L      : {L:.6g}  (average units in the system)",
    "queuing.etiqueta.summary.utilizacion_servidor": "ρ      : {rho:.6g}  (utilization per server)",
    "queuing.etiqueta.summary.wq_tiempo_promedio_espera_cola": "Wq     : {Wq:.6g}  (average waiting time in queue)",
    "queuing.modelo.kingman.kingman": "G/G/1 (Kingman)",
    "queuing.modelo.mmc.texto": "M/M/{c}",
    "reliability.aviso.weibull_mle_beta.forma_estimada_menor_igual_cota": "The estimated shape β is less than or equal to the lower bound {lo:g}; the result is the edge of the search interval, not an exact likelihood maximum.",
    "reliability.aviso.weibull_mle_beta.tiempos_falla_casi_tienen_dispersion": "The failure times have almost no dispersion: the shape β exceeds the bound {hi:g}; the result is the edge of the search interval, not the exact estimator.",
    "reliability.cabecera.to_frame.componentes": "Components",
    "reliability.cabecera.to_frame.disponibilidad": "Availability",
    "reliability.cabecera.to_frame.escala": "η (scale)",
    "reliability.cabecera.to_frame.forma": "β (shape)",
    "reliability.cabecera.to_frame.metodo": "method",
    "reliability.cabecera.to_frame.texto": "R(t={t})",
    "reliability.cabecera.to_frame.topologia": "Topology",
    "reliability.clave_params.koon_system.texto": "k",
    "reliability.error.b_life.pct_debe_estar_estrictamente_entre": "'pct' must be strictly between 0 and 100.",
    "reliability.error.koon_system.debe_cumplirse": "1 ≤ k ≤ n must hold (k={k}, n={n}).",
    "reliability.error.r_system.topologia_desconocida": "Unknown topology: {topology!r}",
    "reliability.error.weibull_analysis.method_debe_ser_mle_rry": "'method' must be 'MLE' or 'RRY'.",
    "reliability.error.weibull_analysis.todos_tiempos_falla_son_iguales": "All failure times are equal: the dispersion is zero and the shape β cannot be estimated.",
    "reliability.etiqueta.summary.componentes": "Components      : {n_components}",
    "reliability.etiqueta.summary.disponibilidad": "Availability    : {availability:.4%}",
    "reliability.etiqueta.summary.metodo_forma_escala_mttf_vida": "Method       : {method} (n={n})\nShape β      : {shape:.4f}\nScale η      : {scale:.4g}\nMTTF         : {mttf:.4g}\nB10 life     : {b10:.4g}\nB50 (median) : {b50:.4g}",
    "reliability.etiqueta.summary.mtbf": "MTBF            : {mtbf:.6g}",
    "reliability.etiqueta.summary.tasas_falla": "Failure rates λ : {expr}",
    "reliability.etiqueta.summary.texto": "R(t={t:.4g})       : {R_t:.6g}",
    "reliability.etiqueta.summary.topologia": "Topology        : {topology}",
    "scheduling.cabecera.to_frame.fin": "M{expr}_end",
    "scheduling.cabecera.to_frame.inicio": "M{expr}_start",
    "scheduling.cabecera.to_frame.inicio_2": "Start",
    "scheduling.cabecera.to_frame.m1_fin": "M1 end",
    "scheduling.cabecera.to_frame.m1_inicio": "M1 start",
    "scheduling.cabecera.to_frame.m2_fin": "M2 end",
    "scheduling.cabecera.to_frame.m2_inicio": "M2 start",
    "scheduling.cabecera.to_frame.retraso": "Tardy",
    "scheduling.cabecera.to_frame.trabajo": "Job",
    "scheduling.error.johnson_flowshop.m1_times_m2_times_deben": "m1_times and m2_times must have the same length.",
    "scheduling.error.neh_flowshop.cada_trabajo_debe_tener_tiempos": "Each job must have processing times for at least one machine.",
    "scheduling.error.neh_flowshop.names_debe_tener_misma_longitud": "'names' must have the same length as 'times_matrix'.",
    "scheduling.error.neh_flowshop.times_matrix_debe_contener_menos": "'times_matrix' must contain at least one job.",
    "scheduling.error.neh_flowshop.todas_filas_deben_tener_misma": "All rows must have the same length; row {i} has {expr} ≠ {m_cnt}.",
    "scheduling.error.schedule_single.rule_debe_ser": "'rule' must be one of {valid}.",
    "scheduling.error.schedule_single.rule_requiere_due_dates": "rule='{rule}' requires due_dates.",
    "scheduling.error.schedule_single.todas_secuencias_entrada_deben_tener": "All input sequences must have the same length.",
    "scheduling.etiqueta.summary.algoritmo_heuristica_neh_maquinas_secuencia": "Algorithm : NEH heuristic\nMachines  : {n_machines}\nSequence  : {expr}\nMakespan  : {makespan:.4g}",
    "scheduling.etiqueta.summary.finalizacion_pond_wcj": "Weighted completion ΣwCj : {total_weighted_completion_time:.4g}",
    "scheduling.etiqueta.summary.finalizacion_total_cj": "Total completion ΣCj     : {total_completion_time:.4g}",
    "scheduling.etiqueta.summary.makespan_cmax": "Makespan (Cmax)          : {makespan:.4g}",
    "scheduling.etiqueta.summary.regla": "Rule                     : {rule}",
    "scheduling.etiqueta.summary.retraso_maximo": "Maximum lateness         : {max_lateness:.4g}",
    "scheduling.etiqueta.summary.secuencia": "Sequence                 : {expr}",
    "scheduling.etiqueta.summary.secuencia_makespan": "Sequence  : {expr}\nMakespan  : {makespan:.4g}",
    "scheduling.etiqueta.summary.tardanza_total_tj": "Total tardiness ΣTj      : {total_tardiness:.4g}",
    "scheduling.etiqueta.summary.trabajos_retraso": "Tardy jobs               : {n_tardy}",
    "scheduling.valor_por_defecto.schedule_single.texto": "J{expr}",
    "solver.clave_params.optimize_servers.cost_per_server": "cost_per_server",
    "solver.clave_params.optimize_servers.cost_per_wait": "cost_per_wait",
    "solver.clave_params.solve_lam.model": "model",
    "solver.clave_params.solve_lam.mu": "mu",
    "solver.clave_params.solve_mu.lam": "lam",
    "solver.error.batch_model.errors_debe_ser_collect_raise": "'errors' must be 'collect' or 'raise'.",
    "solver.error.bisect.raiz_esta_acotada_objetivo_puede": "The root is not bracketed: f({a:.6g})={fa:.4g}, f({b:.6g})={fb:.4g}. The target may be outside the feasible range.",
    "solver.error.get_metric.metrica_desconocida_opciones_validas": "Unknown metric '{metric}'. Valid options: {valid}",
    "solver.error.solve_lam.modelo_desconocido_elija_entre": "Unknown model '{model}'. Choose from {expr}.",
    "solver.error.solve_lam.supera_incluso_muy_baja_objetivo": "{target_metric} exceeds {target_value} even with a very low λ. The target may be infeasible for this model / μ.",
    "solver.error.solve_mu.sigue_superando_objetivo_puede_ser": "{target_metric} still exceeds {target_value} with μ = {mu_max:.4g}. The target may be numerically infeasible.",
    "solver.error.solve_servers.pudo_cumplir_hasta_servidores_considere": "Could not meet {target_metric} ≤ {target_value} with up to {c_max} servers. Consider increasing μ or relaxing the target.",
    "solver.error.optimize_servers.sin_servidores_estables_hasta_c_max": "With λ={lam} and μ={mu} at least {c_min} servers are needed for the system to be stable, but c_max={c_max}. Increase c_max.",
    "solver.error.sensitivity.values_no_puede_estar_vacio": "values cannot be empty.",
    "solver.error.sensitivity.param_no_es_parametro_modelo": "{param!r} is not a parameter of {modelo}.",
    "solver.error.compare.sin_resultados": "compare needs at least one result.",
    "solver.etiqueta.compare.escenario": "scenario_{expr}",
    "solver.etiqueta.summary.convergio": "did NOT converge",
    "solver.etiqueta.summary.convergio_2": "converged",
    "solver.etiqueta.summary.servidores_optimos_costo_minimo_unidad": "Optimal servers    : {optimal_servers}\nMinimum cost       : {min_cost:.6g} per unit of time\n",
    "solver.etiqueta.summary.solver_parametro_resuelto_metrica_objetivo": "Solver [{status}]\n  Solved parameter   : {param} = {value:.6g}\n  Target metric      : {target_metric} ≤ {target_value:.6g}\n  Achieved           : {target_metric2} = {achieved_value:.6g}",
    "utils.error.as_finite_scalar.debe_ser_numero_finito_recibio": "'{name}' must be a finite number, got {value!r}.",
    "utils.error.as_float_list.debe_contener_menos_elementos_recibieron": "'{name}' must contain at least {min_len} elements, got {expr}.",
    "utils.error.as_float_list.debe_ser_secuencia_numeros_recibio": "'{name}' must be a sequence of numbers, got {__name__!r}.",
    "utils.error.as_fraction.debe_ser_valor_finito_recibio": "'{name}' must be a finite value in [0, 1], got {value!r}.",
    "utils.error.as_int_positive.debe_ser_entero_positivo_recibio": "'{name}' must be a positive integer, got {__name__!r} = {value!r}.",
    "utils.error.as_int_positive.debe_ser_recibio": "'{name}' must be >= 1, got {value!r}.",
    "utils.error.as_int_positive.puede_superar_recibio": "'{name}' cannot exceed {max}, got {value!r}.",
    "utils.error.as_nonempty.debe_contener_menos_elemento": "'{name}' must contain at least one element.",
    "utils.error.as_nonneg.debe_ser_finito_recibio": "'{name}' must be finite and >= 0, got {value!r}.",
    "utils.error.as_positive.debe_ser_numero_finito_positivo": "'{name}' must be a finite positive number, got {value!r}.",
    "utils.error.to_float.debe_ser_numero_recibio": "'{name}' must be a number, got {__name__!r}.",
    "utils.error.to_float.debe_ser_numero_recibio_booleano": "'{name}' must be a number, got a boolean ({value!r}).",
}

# Texts that are identical in both languages on purpose (symbols, identifiers, proper names, data keys). Anything else equal to the Spanish text is "untranslated".
EXENTAS_DE_TRADUCCION: frozenset[str] = frozenset({
    "advanced.cabecera.to_frame.wq_p50",
    "advanced.cabecera.to_frame.wq_p90",
    "advanced.cabecera.to_frame.wq_p95",
    "advanced.cabecera.to_frame.wq_p99",
    "advanced.clave_params.break_even_multi.fixed_cost",
    "advanced.clave_params.break_even_multi.products",
    "advanced.clave_params.mm1_priority.residual",
    "advanced.clave_params.monte_carlo_gg1.ca2",
    "advanced.clave_params.monte_carlo_gg1.cs2",
    "advanced.clave_params.monte_carlo_gg1.seed",
    "advanced.modelo.mm1k.texto",
    "advanced.modelo.mmck.texto",
    "advanced.texto_en_expresion.summary.cv",
    "advanced.texto_en_expresion.summary.lq",
    "advanced.texto_en_expresion.summary.texto",
    "advanced.texto_en_expresion.summary.texto_2",
    "advanced.texto_en_expresion.summary.wq",
    "bottleneck.texto_en_expresion.summary.util",
    "columnas.columna_df.global.lam",
    "columnas.columna_df.global.mu",
    "columnas.columna_df.global.texto",
    "columnas.columna_df.global.texto_2",
    "columnas.columna_df.global.texto_3",
    "columnas.columna_df.global.texto_4",
    "fitting.cabecera.to_frame.ca2",
    "fitting.cabecera.to_frame.cs2",
    "inventory.cabecera.modulo.eoq",
    "inventory.cabecera.modulo.sigma_dlt",
    "inventory.clave_params.ebq.production_rate",
    "inventory.clave_params.ebq.setup_cost",
    "inventory.clave_params.eoq.demand_rate",
    "inventory.clave_params.eoq.holding_cost",
    "inventory.clave_params.eoq.ordering_cost",
    "inventory.clave_params.eoq_multi.items",
    "inventory.clave_params.eoq_quantity_discount.holding_cost_rate",
    "inventory.clave_params.newsvendor.cost",
    "inventory.clave_params.newsvendor.demand_mean",
    "inventory.clave_params.newsvendor.price",
    "inventory.clave_params.newsvendor.salvage",
    "inventory.clave_params.reorder_point.demand_std",
    "inventory.clave_params.reorder_point.lead_time",
    "inventory.clave_params.reorder_point.lead_time_std",
    "inventory.clave_params.rs_policy.review_period",
    "inventory.etiqueta.exchange_curve.eoq",
    "inventory.etiqueta.safety_stock_curve.base",
    "inventory.etiqueta.summary.abc_xyz_total",
    "inventory.etiqueta.summary.cv",
    "inventory.etiqueta.summary.cv_2",
    "inventory.etiqueta.summary.cv_3",
    "inventory.etiqueta.summary.texto",
    "inventory.etiqueta.summary.texto_2",
    "inventory.etiqueta.summary.texto_3",
    "inventory.etiqueta.summary.texto_5",
    "inventory.etiqueta.summary.texto_6",
    "inventory.etiqueta.summary.texto_7",
    "inventory.etiqueta.summary.total",
    "inventory.modelo.silver_meal.silver_meal",
    "inventory.modelo.wagner_whitin.wagner_whitin",
    "inventory.valor_por_defecto.exchange_curve.texto",
    "kpi.kpi.oee_kpi_tree.oee",
    "kpi.kpi.oee_kpi_tree.texto",
    "kpi.kpi.roi_kpi_tree.roi",
    "main.cli.main.error",
    "main.cli.main.walopy",
    "network.cabecera.to_frame.ext",
    "network.cabecera.to_frame.total",
    "network.clave_params.jackson_network.texto",
    "network.clave_params.jackson_network.total_gamma",
    "network.texto_en_expresion.summary.ext",
    "network.texto_en_expresion.summary.lq",
    "network.texto_en_expresion.summary.texto",
    "network.texto_en_expresion.summary.texto_2",
    "network.texto_en_expresion.summary.tot",
    "network.texto_en_expresion.summary.wq",
    "operations.cabecera.to_frame.throughput",
    "operations.etiqueta.summary.oee",
    "plotting.grafica.collect.br",
    "plotting.grafica.collect.br_2",
    "plotting.grafica.plot_eoq.eoq",
    "plotting.grafica.plot_kpi_tree.customdata_extra_extra",
    "plotting.grafica.plot_line_balance.takt",
    "plotting.grafica.plot_queue_distribution.nn",
    "plotting.grafica.plot_queue_distribution.texto",
    "plotting.grafica.plot_queue_distribution.texto_2",
    "plotting.grafica.plot_queue_distribution.texto_3",
    "plotting.grafica.plot_queue_distribution.texto_4",
    "plotting.grafica.plot_simulation.wq",
    "queuing.clave_params.mmc.erlang",
    "queuing.modelo.kingman.kingman",
    "queuing.modelo.mmc.texto",
    "reliability.cabecera.to_frame.texto",
    "reliability.clave_params.koon_system.texto",
    "reliability.etiqueta.summary.mtbf",
    "reliability.etiqueta.summary.texto",
    "scheduling.valor_por_defecto.schedule_single.texto",
    "solver.clave_params.optimize_servers.cost_per_server",
    "solver.clave_params.optimize_servers.cost_per_wait",
    "solver.clave_params.solve_lam.model",
    "solver.clave_params.solve_lam.mu",
    "solver.clave_params.solve_mu.lam",
})
