"""Catálogo de textos en español (idioma por defecto). Claves: ``modulo.tipo.funcion.resumen``; marcadores ``{nombre}`` de ``str.format``."""
from __future__ import annotations

ES: dict[str, str] = {
    "advanced.cabecera.to_frame.clientes": "N clientes",
    "advanced.cabecera.to_frame.id_clase": "id_clase",
    "advanced.cabecera.to_frame.margen_contribucion": "Margen de contribución",
    "advanced.cabecera.to_frame.margen_seguridad": "Margen de seguridad (%)",
    "advanced.cabecera.to_frame.margen_seguridad_unidades": "Margen de seguridad (unidades)",
    "advanced.cabecera.to_frame.medio": "W medio",
    "advanced.cabecera.to_frame.pe_ingresos": "PE (ingresos)",
    "advanced.cabecera.to_frame.pe_unidades": "PE (unidades)",
    "advanced.cabecera.to_frame.razon_mc": "Razón MC",
    "advanced.cabecera.to_frame.wq_medio": "Wq medio",
    "advanced.cabecera.to_frame.wq_p50": "Wq p50",
    "advanced.cabecera.to_frame.wq_p90": "Wq p90",
    "advanced.cabecera.to_frame.wq_p95": "Wq p95",
    "advanced.cabecera.to_frame.wq_p99": "Wq p99",
    "advanced.clave_params.break_even_multi.fixed_cost": "fixed_cost",
    "advanced.clave_params.break_even_multi.products": "n_products",
    "advanced.clave_params.mm1_priority.clases": "N_clases",
    "advanced.clave_params.mm1_priority.residual": "R (residual)",
    "advanced.clave_params.mm1k.capacidad": "K (capacidad)",
    "advanced.clave_params.mm1k.eff_tasa_efectiva": "λ_eff (tasa efectiva)",
    "advanced.clave_params.mm1k.p0_vacio": "P0 (vacío)",
    "advanced.clave_params.mm1k.pk_prob_bloqueo": "PK (prob. de bloqueo)",
    "advanced.clave_params.monte_carlo_gg1.ca2": "ca2",
    "advanced.clave_params.monte_carlo_gg1.cs2": "cs2",
    "advanced.clave_params.monte_carlo_gg1.seed": "seed",
    "advanced.error.break_even.price_per_unit_debe_superar": "price_per_unit debe superar a variable_cost_per_unit para obtener un margen de contribución positivo.",
    "advanced.error.break_even_multi.names_debe_tener_misma_longitud": "'names' debe tener la misma longitud que prices.",
    "advanced.error.break_even_multi.prices_variable_costs_sales_mix": "prices, variable_costs y sales_mix deben tener la misma longitud.",
    "advanced.error.break_even_multi.suma_sales_mix_debe_ser": "La suma de sales_mix debe ser positiva.",
    "advanced.error.break_even_multi.todos_productos_deben_tener_margen": "Todos los productos deben tener margen de contribución positivo (precio > costo variable).",
    "advanced.error.break_even_sales.variable_cost_ratio_debe_estar": "'variable_cost_ratio' debe estar estrictamente entre 0 y 1.",
    "advanced.error.line_balance.station_names_cycle_times_deben": "'station_names' y 'cycle_times' deben tener la misma longitud.",
    "advanced.error.mm1_priority.class_names_debe_tener_misma": "'class_names' debe tener la misma longitud que 'lam_list'.",
    "advanced.error.mm1_priority.lam_list_debe_contener_menos": "'lam_list' debe contener al menos una clase.",
    "advanced.error.mm1_priority.sistema_inestable_total": "Sistema inestable: ρ_total = {rho_total:.4g} ≥ 1.",
    "advanced.error.mmck.capacidad_sistema_debe_ser_servidores": "'K' (capacidad del sistema) debe ser ≥ c (servidores); se recibió K={K}, c={c}.",
    "advanced.error.monte_carlo_gg1.sistema_inestable": "Sistema inestable: ρ = {rho:.4g} ≥ 1.",
    "advanced.error.queue_length_pmf.max_debe_estar_entre_recibio": "'n_max' debe estar entre 0 y {MAX_ESTADOS}, se recibió {n_max!r}.",
    "advanced.error.queue_length_pmf.max_debe_ser_entero_recibio": "'n_max' debe ser un entero >= 0, se recibió {__name__!r}.",
    "advanced.etiqueta.summary.margen_contribucion": "Margen de contribución        : {contribution_margin:.4g}",
    "advanced.etiqueta.summary.margen_seguridad_unidades": "Margen de seguridad           : {margin_of_safety_units:.4g} unidades ({margin_of_safety_pct:.2%})",
    "advanced.etiqueta.summary.mc_ponderado_promedio": "MC ponderado promedio                 : {weighted_avg_cm:.4g}",
    "advanced.etiqueta.summary.modelo_wq_medio_p50_p90": "Modelo   : {model}\nN        : {n_customers:,}\nρ        : {rho:.4f}\nWq medio : {Wq_mean:.6g}  (p50={Wq_p50:.4g}  p90={Wq_p90:.4g}  p95={Wq_p95:.4g}  p99={Wq_p99:.4g})\nW medio  : {W_mean:.6g}\nLq       : {Lq:.6g}\nL        : {L:.6g}",
    "advanced.etiqueta.summary.prioridad_hol_expropiativa": "M/M/1 con prioridad HOL no expropiativa  (μ={mu:.6g}, ρ={rho_total:.4g})",
    "advanced.etiqueta.summary.punto_equilibrio_ingresos": "Punto de equilibrio (ingresos): {bep_revenue:.4g}",
    "advanced.etiqueta.summary.punto_equilibrio_ingresos_totales": "Punto de equilibrio (ingresos totales): {bep_revenue_total:.4g}",
    "advanced.etiqueta.summary.punto_equilibrio_unidades": "Punto de equilibrio (unidades): {bep_units:.4g}",
    "advanced.etiqueta.summary.punto_equilibrio_unidades_totales": "Punto de equilibrio (unidades totales): {bep_units_total:.4g}",
    "advanced.etiqueta.summary.razon_contribucion": "Razón de contribución         : {contribution_margin_ratio:.2%}",
    "advanced.etiqueta.summary.razon_mc_ponderada": "Razón MC ponderada                    : {cm_ratio_weighted:.2%}",
    "advanced.etiqueta.summary.tiempo_takt_estaciones_minimo_teorico": "Tiempo takt             : {takt:.6g}\nEstaciones              : {n_stations}\nMínimo teórico          : {theoretical_min_stations}\nEficiencia de balance   : {balance_efficiency:.2%}\nEstación cuello de botella: {bottleneck}\n",
    "advanced.modelo.mm1k.texto": "M/M/1/{K}",
    "advanced.modelo.mmck.texto": "M/M/{c}/{K}",
    "advanced.modelo.monte_carlo_gg1.simulacion_ca2_cs2": "Simulación G/G/1 (ca²={ca2:.3g}, cs²={cs2:.3g})",
    "advanced.texto_en_expresion.summary.clase": "Clase",
    "advanced.texto_en_expresion.summary.cv": "CV",
    "advanced.texto_en_expresion.summary.lq": "Lq",
    "advanced.texto_en_expresion.summary.mc": "MC",
    "advanced.texto_en_expresion.summary.mezcla": "Mezcla",
    "advanced.texto_en_expresion.summary.pe_ingr": "PE ingr.",
    "advanced.texto_en_expresion.summary.pe_unid": "PE unid.",
    "advanced.texto_en_expresion.summary.precio": "Precio",
    "advanced.texto_en_expresion.summary.producto": "Producto",
    "advanced.texto_en_expresion.summary.texto": "L",
    "advanced.texto_en_expresion.summary.texto_2": "W",
    "advanced.texto_en_expresion.summary.wq": "Wq",
    "advanced.valor_por_defecto.break_even_multi.producto": "Producto-{expr}",
    "bottleneck.cabecera.to_frame.capacidad": "Capacidad",
    "bottleneck.cabecera.to_frame.cuello_botella": "Cuello de botella",
    "bottleneck.cabecera.to_frame.estacion": "Estación",
    "bottleneck.cabecera.to_frame.holgura": "Holgura",
    "bottleneck.cabecera.to_frame.tasa_demanda": "Tasa de demanda",
    "bottleneck.cabecera.to_frame.utilizacion": "Utilización",
    "bottleneck.error.bottleneck_analysis.routing_fractions_debe_tener_valor": "'routing_fractions' debe tener un valor por estación.",
    "bottleneck.error.bottleneck_analysis.station_names_capacities_deben_tener": "'station_names' y 'capacities' deben tener la misma longitud.",
    "bottleneck.etiqueta.summary.cb": " ← CB",
    "bottleneck.etiqueta.summary.estacion_cuello_botella": "Estación cuello de botella: {bottleneck}",
    "bottleneck.etiqueta.summary.tasa_demanda": "Tasa de demanda           : {demand_rate:.6g}",
    "bottleneck.etiqueta.summary.throughput_sistema": "Throughput del sistema    : {system_throughput:.6g}",
    "bottleneck.texto_en_expresion.summary.capacidad": "Capacidad",
    "bottleneck.texto_en_expresion.summary.demanda": "Demanda",
    "bottleneck.texto_en_expresion.summary.estacion": "Estación",
    "bottleneck.texto_en_expresion.summary.holgura": "Holgura",
    "bottleneck.texto_en_expresion.summary.util": "Util.",
    "columnas.columna_df.global.ajustada": "Q ajustada",
    "columnas.columna_df.global.articulo": "Artículo",
    "columnas.columna_df.global.cantidad_min": "Cantidad mín.",
    "columnas.columna_df.global.costo_compra": "Costo de compra",
    "columnas.columna_df.global.costo_mantener": "Costo de mantener",
    "columnas.columna_df.global.costo_ordenar": "Costo de ordenar",
    "columnas.columna_df.global.costo_preparacion": "Costo de preparación",
    "columnas.columna_df.global.costo_total": "Costo total",
    "columnas.columna_df.global.costo_variable": "Costo variable",
    "columnas.columna_df.global.estacion": "Estación",
    "columnas.columna_df.global.factible": "Factible",
    "columnas.columna_df.global.frecuencia_lotes": "Frecuencia de lotes",
    "columnas.columna_df.global.frecuencia_pedidos": "Frecuencia de pedidos",
    "columnas.columna_df.global.indice_tramo": "Índice de tramo",
    "columnas.columna_df.global.inventario_maximo": "Inventario máximo",
    "columnas.columna_df.global.inventario_promedio": "Inventario promedio",
    "columnas.columna_df.global.lam": "lam",
    "columnas.columna_df.global.mezcla": "Mezcla",
    "columnas.columna_df.global.mu": "mu",
    "columnas.columna_df.global.pe_ingresos": "PE ingresos",
    "columnas.columna_df.global.pe_unidades": "PE unidades",
    "columnas.columna_df.global.precio": "Precio",
    "columnas.columna_df.global.precio_unitario": "Precio unitario",
    "columnas.columna_df.global.producto": "Producto",
    "columnas.columna_df.global.servidores": "c (servidores)",
    "columnas.columna_df.global.sobrecargada": "Sobrecargada",
    "columnas.columna_df.global.texto": "P(N<=n)",
    "columnas.columna_df.global.texto_2": "P(N=n)",
    "columnas.columna_df.global.texto_3": "F(t)",
    "columnas.columna_df.global.texto_4": "f(t)",
    "columnas.columna_df.global.tiempo_ciclo": "Tiempo_ciclo",
    "columnas.columna_df.global.tiempo_ciclo_2": "Tiempo de ciclo",
    "columnas.columna_df.global.tiempo_ocioso": "Tiempo_ocioso",
    "columnas.columna_df.global.utilizacion": "Utilización",
    "fitting.cabecera.to_frame.ca2": "ca²",
    "fitting.cabecera.to_frame.cs2": "cs²",
    "fitting.error.fit_from_data.arrival_timestamps_debe_contener_menos": "'arrival_timestamps' debe contener al menos 2 marcas de tiempo.",
    "fitting.error.fit_from_data.arrival_timestamps_debe_ser_finito": "'arrival_timestamps' debe ser finito.",
    "fitting.error.fit_from_data.indique_inter_arrivals_arrival_timestamps": "Indique 'inter_arrivals' o 'arrival_timestamps', no ambos.",
    "fitting.error.fit_from_data.indique_menos_uno_inter_arrivals": "Indique al menos uno de 'inter_arrivals', 'arrival_timestamps' o 'service_times'.",
    "fitting.error.fit_times.debe_contener_menos_observaciones": "'{name}' debe contener al menos 2 observaciones.",
    "fitting.error.fit_times.todos_valores_deben_ser_finitos": "Todos los valores de '{name}' deben ser finitos y estrictamente positivos.",
    "fitting.etiqueta.summary.ajuste_fitresult": "Ajuste (FitResult)",
    "fitting.etiqueta.summary.ca2_cv2_llegadas": "  ca² (CV² de llegadas)   : {ca2:.6g}",
    "fitting.etiqueta.summary.cs2_cv2_servicio": "  cs² (CV² de servicio)   : {cs2:.6g}",
    "fitting.etiqueta.summary.desv_entre_llegadas": "  desv. entre llegadas    : {std_ia:.6g}",
    "fitting.etiqueta.summary.desv_servicio": "  desv. de servicio       : {std_svc:.6g}",
    "fitting.etiqueta.summary.media_entre_llegadas": "  media entre llegadas    : {mean_ia:.6g}",
    "fitting.etiqueta.summary.media_servicio": "  media de servicio       : {mean_svc:.6g}",
    "fitting.etiqueta.summary.tasa_llegada": "  λ (tasa de llegada)     : {lam:.6g}  (n={n_arrivals})",
    "fitting.etiqueta.summary.tasa_servicio": "  μ (tasa de servicio)    : {mu:.6g}  (n={n_services})",
    "i18n.error.validar.idioma_no_admitido": "Idioma no admitido: {lang!r}. Opciones: {opciones}.",
    "inventory.aviso.mrp.unidades_planificadas_debieron_liberarse_antes": "{past_due:g} unidades planificadas debieron liberarse antes del periodo 1 (lead_time={lead_time} no cabe en el horizonte); consulte 'past_due_releases'.",
    "inventory.cabecera.modulo.articulo": "artículo",
    "inventory.cabecera.modulo.cantidad_pedido": "cantidad_pedido",
    "inventory.cabecera.modulo.clase": "clase",
    "inventory.cabecera.modulo.clase_abc": "clase_abc",
    "inventory.cabecera.modulo.clase_combinada": "clase_combinada",
    "inventory.cabecera.modulo.clase_xyz": "clase_xyz",
    "inventory.cabecera.modulo.demanda": "demanda",
    "inventory.cabecera.modulo.eoq": "Q_eoq",
    "inventory.cabecera.modulo.indice": "índice",
    "inventory.cabecera.modulo.inversion": "I (inversión)",
    "inventory.cabecera.modulo.inversion_2": "inversión",
    "inventory.cabecera.modulo.inversion_ss": "inversión_ss",
    "inventory.cabecera.modulo.nivel_servicio": "nivel_de_servicio",
    "inventory.cabecera.modulo.optima": "Q_óptima",
    "inventory.cabecera.modulo.pct_acumulado": "pct_acumulado",
    "inventory.cabecera.modulo.pct_valor": "pct_valor",
    "inventory.cabecera.modulo.pedidos": "n_pedidos",
    "inventory.cabecera.modulo.pedidos_ano": "N (pedidos/año)",
    "inventory.cabecera.modulo.periodo": "periodo",
    "inventory.cabecera.modulo.periodos_cubiertos": "periodos_cubiertos",
    "inventory.cabecera.modulo.posicion": "posición",
    "inventory.cabecera.modulo.punto_reorden": "punto_de_reorden",
    "inventory.cabecera.modulo.sigma_dlt": "sigma_dlt",
    "inventory.cabecera.modulo.stock_seguridad": "stock_de_seguridad",
    "inventory.cabecera.modulo.valor_anual": "valor_anual",
    "inventory.cabecera.modulo.valor_unitario": "valor_unitario",
    "inventory.cabecera.to_frame.costo_mantener": "Costo de mantener",
    "inventory.cabecera.to_frame.costo_ordenar": "Costo de ordenar",
    "inventory.cabecera.to_frame.costo_preparacion": "Costo de preparación",
    "inventory.cabecera.to_frame.costo_total": "Costo total",
    "inventory.cabecera.to_frame.demanda_media_lt": "Demanda media en LT",
    "inventory.cabecera.to_frame.desv_demanda_lt": "Desv. demanda en LT",
    "inventory.cabecera.to_frame.exist_proy": "Exist_proy",
    "inventory.cabecera.to_frame.faltante_esperado": "Faltante esperado",
    "inventory.cabecera.to_frame.frecuencia_lotes": "Frecuencia de lotes",
    "inventory.cabecera.to_frame.frecuencia_pedidos": "Frecuencia de pedidos",
    "inventory.cabecera.to_frame.inventario_maximo": "Inventario máximo",
    "inventory.cabecera.to_frame.inventario_promedio": "Inventario promedio",
    "inventory.cabecera.to_frame.lib_plan": "Lib_plan",
    "inventory.cabecera.to_frame.nivel_servicio": "Nivel de servicio",
    "inventory.cabecera.to_frame.periodo": "Periodo",
    "inventory.cabecera.to_frame.punto_reorden": "Punto de reorden",
    "inventory.cabecera.to_frame.razon_critica": "Razón crítica",
    "inventory.cabecera.to_frame.recep_plan": "Recep_plan",
    "inventory.cabecera.to_frame.recep_prog": "Recep_prog",
    "inventory.cabecera.to_frame.req_bruto": "Req_bruto",
    "inventory.cabecera.to_frame.req_neto": "Req_neto",
    "inventory.cabecera.to_frame.sobrante_esperado": "Sobrante esperado",
    "inventory.cabecera.to_frame.stock_seguridad": "Stock de seguridad",
    "inventory.cabecera.to_frame.tiempo_ciclo": "Tiempo de ciclo",
    "inventory.cabecera.to_frame.utilidad_esperada": "Utilidad esperada",
    "inventory.cabecera.to_frame.ventas_esperadas": "Ventas esperadas",
    "inventory.clave_params.ebq.production_rate": "production_rate",
    "inventory.clave_params.ebq.setup_cost": "setup_cost",
    "inventory.clave_params.eoq.demand_rate": "demand_rate",
    "inventory.clave_params.eoq.holding_cost": "holding_cost",
    "inventory.clave_params.eoq.ordering_cost": "ordering_cost",
    "inventory.clave_params.eoq_multi.items": "n_items",
    "inventory.clave_params.eoq_quantity_discount.holding_cost_rate": "holding_cost_rate",
    "inventory.clave_params.newsvendor.cost": "cost",
    "inventory.clave_params.newsvendor.demand_mean": "demand_mean",
    "inventory.clave_params.newsvendor.price": "price",
    "inventory.clave_params.newsvendor.salvage": "salvage",
    "inventory.clave_params.reorder_point.demand_std": "demand_std",
    "inventory.clave_params.reorder_point.lead_time": "lead_time",
    "inventory.clave_params.reorder_point.lead_time_std": "lead_time_std",
    "inventory.clave_params.rs_policy.review_period": "review_period",
    "inventory.error.abc_analysis.debe_cumplirse_threshold_threshold": "Debe cumplirse 0 < a_threshold < b_threshold < 1.",
    "inventory.error.abc_analysis.valor_anual_total_cero_todas": "El valor anual total es cero (todas las demandas son 0): no hay nada que clasificar.",
    "inventory.error.clave.falta_clave": "{nombre}[{i}]: falta la clave '{clave}'.",
    "inventory.error.ebq.production_rate_debe_superar_demand": "production_rate ({P}) debe superar a demand_rate ({D}).",
    "inventory.error.eoq_lagrangian_bisect.restriccion_puede_satisfacer_ninguna_cantidad": "La restricción no se puede satisfacer con ninguna cantidad de pedido positiva.",
    "inventory.error.eoq_multi.todas_secuencias_entrada_deben_tener": "Todas las secuencias de entrada deben tener la misma longitud.",
    "inventory.error.eoq_multi_constrained.budget_unit_costs_debe_tener": "'budget_unit_costs' debe tener la misma longitud que demand_rates.",
    "inventory.error.eoq_multi_constrained.budget_unit_costs_obligatorio_cuando": "'budget_unit_costs' es obligatorio cuando se indica 'budget'.",
    "inventory.error.eoq_multi_constrained.constraints_debe_ser_diccionario_name": "constraints[{j}] debe ser un diccionario con 'name', 'weights' y 'bound'.",
    "inventory.error.eoq_multi_constrained.restriccion_weights_tiene_longitud_distinta": "La restricción '{expr}': 'weights' tiene una longitud distinta a demand_rates.",
    "inventory.error.eoq_multi_constrained.space_per_unit_debe_tener": "'space_per_unit' debe tener la misma longitud que demand_rates.",
    "inventory.error.eoq_multi_constrained.space_per_unit_obligatorio_cuando": "'space_per_unit' es obligatorio cuando se indica 'space'.",
    "inventory.error.eoq_quantity_discount.feasible_price_break_found": "No se encontró ningún tramo de precio factible.",
    "inventory.error.eoq_quantity_discount.price_breaks_debe_contener_menos": "price_breaks debe contener al menos una entrada.",
    "inventory.error.exchange_curve.indique_como_maximo_uno_target": "Indique como máximo uno de 'target_orders' o 'target_investment'.",
    "inventory.error.exchange_curve.items_debe_contener_menos_elemento": "'items' debe contener al menos un elemento.",
    "inventory.error.exchange_curve.items_unit_value_debe_ser": "items[{idx}]['unit_value'] debe ser > 0.",
    "inventory.error.leer_items.debe_contener_menos_elemento": "'{nombre}' debe contener al menos un elemento.",
    "inventory.error.leer_items.debe_ser_diccionario_recibio": "{nombre}[{i}] debe ser un diccionario, se recibió {__name__!r}.",
    "inventory.error.leer_items.debe_ser_lista_diccionarios_recibio": "'{nombre}' debe ser una lista de diccionarios, se recibió {__name__!r}.",
    "inventory.error.mrp.lead_time_debe_ser_entero": "'lead_time' debe ser un entero no negativo.",
    "inventory.error.mrp.lot_size_debe_ser_lfl": "'lot_size' debe ser 'LFL' o un número positivo.",
    "inventory.error.mrp.periods_debe_tener_misma_longitud": "'periods' debe tener la misma longitud que 'gross_requirements'.",
    "inventory.error.mrp.scheduled_receipts_debe_tener_misma": "'scheduled_receipts' debe tener la misma longitud que 'gross_requirements'.",
    "inventory.error.newsvendor.cost_debe_ser_menor_price": "'cost' debe ser menor que 'price' (de lo contrario Cu ≤ 0).",
    "inventory.error.newsvendor.salvage_debe_ser_menor_cost": "'salvage' debe ser menor que 'cost' (de lo contrario Co ≤ 0).",
    "inventory.error.reorder_point.service_level_debe_estar_estrictamente": "'service_level' debe estar estrictamente entre 0 y 1.",
    "inventory.error.safety_stock_curve.indique_como_maximo_uno_target": "Indique como máximo uno de 'target_service_level' o 'target_ss_investment'.",
    "inventory.error.safety_stock_curve.items_lead_time_std_debe": "items[{idx}]['lead_time_std'] debe ser ≥ 0.",
    "inventory.error.safety_stock_curve.target_service_level_debe_estar": "'target_service_level' debe estar estrictamente entre 0 y 1.",
    "inventory.error.safety_stock_curve.todos_articulos_tienen_demand_std": "Todos los artículos tienen demand_std=0: el stock de seguridad es siempre 0.",
    "inventory.error.xyz_analysis.debe_cumplirse_threshold_threshold": "Debe cumplirse 0 ≤ x_threshold < y_threshold.",
    "inventory.error.xyz_analysis.items_falta_cv_demand_std": "items[{i}]: falta 'cv' o ('demand_std' y 'demand_mean'/'demand_rate').",
    "inventory.etiqueta.exchange_curve.eoq": "eoq",
    "inventory.etiqueta.exchange_curve.inversion": "inversión={ti:.4g}",
    "inventory.etiqueta.exchange_curve.pedidos": "pedidos={to:.4g}",
    "inventory.etiqueta.safety_stock_curve.base": "base (z=0)",
    "inventory.etiqueta.safety_stock_curve.inversion_ss": "inversión_ss={ti:.4g}",
    "inventory.etiqueta.safety_stock_curve.nivel_servicio": "nivel_de_servicio={sl_val:.4%}",
    "inventory.etiqueta.summary.abc_xyz_total": "ABC\\XYZ   X     Y     Z   Total",
    "inventory.etiqueta.summary.articulo": "Artículo: {item_name}",
    "inventory.etiqueta.summary.cantidad_optima_unidades_precio_unitario": "Cantidad óptima    : {optimal_qty:.4g} unidades\nPrecio unitario    : {unit_price:.4g}\nCosto total/año    : {total_cost:.6g}\n  Costo de compra  : {purchase_cost:.6g}\n  Costo de ordenar : {ordering_cost_total:.6g}\n  Costo de mantener: {holding_cost_total:.6g}",
    "inventory.etiqueta.summary.cantidad_optima_unidades_razon_critica": "Cantidad óptima     : {optimal_qty:.4g} unidades\nRazón crítica       : {critical_ratio:.4g}\nUtilidad esperada   : {expected_profit:.6g}\nVentas esperadas    : {expected_sales:.4g}\nSobrante esperado   : {expected_leftover:.4g}\nFaltante esperado   : {expected_stockout:.4g}\nCosto de subestimar Cu: {underage_cost:.4g}\nCosto de sobrestimar Co: {overage_cost:.4g}",
    "inventory.etiqueta.summary.costo_mantener": "  Costo de mantener  : {total_holding_cost:.6g}",
    "inventory.etiqueta.summary.costo_preparacion": "  Costo de preparación: {total_setup_cost:.6g}",
    "inventory.etiqueta.summary.costo_total": "Costo total          : {total_cost:.6g}",
    "inventory.etiqueta.summary.costo_total_2": "\nCosto total: {total_cost:.6g}",
    "inventory.etiqueta.summary.costo_total_restricciones": "Costo total (con restricciones): {total_cost:.6g}",
    "inventory.etiqueta.summary.costo_total_sin_restricciones": "Costo total (sin restricciones) : {unconstrained_total_cost:.6g}",
    "inventory.etiqueta.summary.ct": "  {expr:<16} Q*={expr2:.4g}  CT={expr3:.4g}",
    "inventory.etiqueta.summary.cv": "CV > {expr:.2g}",
    "inventory.etiqueta.summary.cv_2": "CV ≤ {expr:.2g}",
    "inventory.etiqueta.summary.cv_3": "{expr:.2g} < CV ≤ {expr2:.2g}",
    "inventory.etiqueta.summary.ebq_tamano_lote_unidades_inventario": "EBQ (tamaño de lote): {ebq:.4g} unidades\nInventario máximo   : {max_inventory:.4g}\nInventario promedio : {avg_inventory:.4g}\nFrecuencia de lotes : {order_frequency:.4g} lotes/periodo\nTiempo de ciclo     : {cycle_time:.4g} periodos\nTiempo de producción: {production_time:.4g} periodos\nCosto total         : {total_cost:.6g}\n  Costo de mantener : {holding_cost_total:.6g}\n  Costo de preparación: {setup_cost_total:.6g}",
    "inventory.etiqueta.summary.eoq_cantidad_pedido_unidades_frecuencia": "EOQ (cantidad de pedido): {eoq:.4g} unidades\nFrecuencia de pedidos   : {order_frequency:.4g} pedidos/periodo\nTiempo de ciclo         : {cycle_time:.4g} periodos\nCosto total             : {total_cost:.6g}\n  Costo de mantener     : {holding_cost_total:.6g}\n  Costo de ordenar      : {ordering_cost_total:.6g}",
    "inventory.etiqueta.summary.inversion_eoq": "Inversión (EOQ)         : {investment_eoq:.4g}",
    "inventory.etiqueta.summary.inversion_optimo": "Inversión (óptimo)      : {investment_optimal:.4g}",
    "inventory.etiqueta.summary.inversion_ss": "Inversión en SS   : {ss_investment:.4g}",
    "inventory.etiqueta.summary.metodo": "Método               : {method}",
    "inventory.etiqueta.summary.multiplicador": "Multiplicador k         : {multiplier:.4f}",
    "inventory.etiqueta.summary.nivel_servicio": "Nivel de servicio : {service_level:.4%}",
    "inventory.etiqueta.summary.numero_pedidos": "Número de pedidos    : {n_orders}",
    "inventory.etiqueta.summary.objetivo": "Objetivo                : {target}",
    "inventory.etiqueta.summary.objetivo_2": "Objetivo          : {target}",
    "inventory.etiqueta.summary.pedidos_ano_eoq": "N pedidos/año (EOQ)     : {n_orders_eoq:.4g}",
    "inventory.etiqueta.summary.pedidos_ano_optimo": "N pedidos/año (óptimo)  : {n_orders_optimal:.4g}",
    "inventory.etiqueta.summary.politica_revision_continua_cantidad_pedido": "Política (r, Q) de revisión continua\n  Cantidad de pedido Q*: {order_qty:.4g}\n  Punto de reorden r   : {reorder_point:.4g}\n  Stock de seguridad SS: {safety_stock:.4g}\n  Nivel de servicio    : {service_level:.2%}\n  Inventario promedio  : {avg_inventory:.4g}\n  Costo total          : {total_cost:.6g}",
    "inventory.etiqueta.summary.politica_revision_periodica_periodo_revision": "Política (R, S) de revisión periódica\n  Periodo de revisión R: {review_period:.4g}\n  Nivel de reposición S: {order_up_to:.4g}\n  Stock de seguridad SS: {safety_stock:.4g}\n  Nivel de servicio    : {service_level:.2%}\n  Inventario promedio  : {avg_inventory:.4g}\n  Costo total          : {total_cost:.6g}",
    "inventory.etiqueta.summary.punto_reorden_unidades_stock_seguridad": "Punto de reorden    : {reorder_point:.4g} unidades\nStock de seguridad  : {safety_stock:.4g} unidades\nNivel de servicio   : {service_level:.2%}\nz                   : {z_score:.4g}\nDemanda media en LT : {mean_demand_lt:.4g}\nDesv. demanda en LT : {std_demand_lt:.4g}",
    "inventory.etiqueta.summary.restricciones_activas": "Restricciones activas: {expr}",
    "inventory.etiqueta.summary.texto": "A",
    "inventory.etiqueta.summary.texto_2": "B",
    "inventory.etiqueta.summary.texto_3": "C",
    "inventory.etiqueta.summary.texto_4": "z               : {z:.4f}",
    "inventory.etiqueta.summary.texto_5": "X",
    "inventory.etiqueta.summary.texto_6": "Y",
    "inventory.etiqueta.summary.texto_7": "Z",
    "inventory.etiqueta.summary.total": "Total  ",
    "inventory.etiqueta.summary.valor_anual_total": "Valor anual total : {total_value:.6g}",
    "inventory.modelo.lot_for_lot.lote_lote": "Lote por lote",
    "inventory.modelo.silver_meal.silver_meal": "Silver-Meal",
    "inventory.modelo.wagner_whitin.wagner_whitin": "Wagner-Whitin",
    "inventory.texto_en_expresion.summary.artic": "%Artíc.",
    "inventory.texto_en_expresion.summary.artic_2": "Artíc.",
    "inventory.texto_en_expresion.summary.cantidad": "Cantidad",
    "inventory.texto_en_expresion.summary.clase": "Clase",
    "inventory.texto_en_expresion.summary.cubre": "Cubre",
    "inventory.texto_en_expresion.summary.ep": "EP",
    "inventory.texto_en_expresion.summary.lpl": "LPl",
    "inventory.texto_en_expresion.summary.ninguna": "ninguna",
    "inventory.texto_en_expresion.summary.periodo": "Periodo",
    "inventory.texto_en_expresion.summary.rango_cv": "Rango CV",
    "inventory.texto_en_expresion.summary.rb": "RB",
    "inventory.texto_en_expresion.summary.rn": "RN",
    "inventory.texto_en_expresion.summary.rp": "RP",
    "inventory.texto_en_expresion.summary.rpl": "RPl",
    "inventory.texto_en_expresion.summary.valor": "%Valor",
    "inventory.valor_por_defecto.abc_analysis.articulo": "Artículo{expr}",
    "inventory.valor_por_defecto.eoq_multi.articulo": "Artículo-{expr}",
    "inventory.valor_por_defecto.exchange_curve.texto": "I{expr}",
    "inventory.valor_por_defecto.mrp.articulo": "Artículo",
    "kpi.cabecera.to_frame.formula": "fórmula",
    "kpi.cabecera.to_frame.nivel": "nivel",
    "kpi.cabecera.to_frame.nombre": "nombre",
    "kpi.cabecera.to_frame.unidad": "unidad",
    "kpi.cabecera.to_frame.valor": "valor",
    "kpi.kpi.oee_kpi_tree.calidad": "Calidad",
    "kpi.kpi.oee_kpi_tree.ciclo_ideal_ciclo_real": "Ciclo ideal / Ciclo real",
    "kpi.kpi.oee_kpi_tree.disponibilidad": "Disponibilidad",
    "kpi.kpi.oee_kpi_tree.oee": "OEE",
    "kpi.kpi.oee_kpi_tree.planificado_paradas_planificado": "(Planificado − Paradas) / Planificado",
    "kpi.kpi.oee_kpi_tree.rendimiento": "Rendimiento",
    "kpi.kpi.oee_kpi_tree.texto": "A × P × Q",
    "kpi.kpi.oee_kpi_tree.unidades_buenas_unidades_totales": "Unidades buenas / Unidades totales",
    "kpi.kpi.roi_kpi_tree.costo_fijo": "Costo fijo",
    "kpi.kpi.roi_kpi_tree.costo_fijo_costo_variable": "Costo fijo + Costo variable",
    "kpi.kpi.roi_kpi_tree.costo_total": "Costo total",
    "kpi.kpi.roi_kpi_tree.costo_unidad": "Costo / unidad",
    "kpi.kpi.roi_kpi_tree.costo_unidad_unidades_vendidas": "Costo/unidad × Unidades vendidas",
    "kpi.kpi.roi_kpi_tree.costo_variable": "Costo variable",
    "kpi.kpi.roi_kpi_tree.ingresos": "Ingresos",
    "kpi.kpi.roi_kpi_tree.ingresos_costo_total": "Ingresos − Costo total",
    "kpi.kpi.roi_kpi_tree.inversion": "Inversión",
    "kpi.kpi.roi_kpi_tree.roi": "ROI",
    "kpi.kpi.roi_kpi_tree.unidad": "{currency}/unidad",
    "kpi.kpi.roi_kpi_tree.unidades": "unidades",
    "kpi.kpi.roi_kpi_tree.unidades_vendidas": "Unidades vendidas",
    "kpi.kpi.roi_kpi_tree.utilidad_neta": "Utilidad neta",
    "kpi.kpi.roi_kpi_tree.utilidad_neta_inversion": "Utilidad neta / Inversión",
    "kpi.kpi.throughput_kpi_tree.capacidad": "Capacidad",
    "kpi.kpi.throughput_kpi_tree.real_capacidad": "Real / Capacidad",
    "kpi.kpi.throughput_kpi_tree.real_tasa_defectos": "Real × (1 − Tasa de defectos)",
    "kpi.kpi.throughput_kpi_tree.tasa_buenos": "Tasa de buenos",
    "kpi.kpi.throughput_kpi_tree.tasa_defectos": "1 − Tasa de defectos",
    "kpi.kpi.throughput_kpi_tree.throughput_efectivo": "Throughput efectivo",
    "kpi.kpi.throughput_kpi_tree.throughput_real": "Throughput real",
    "kpi.kpi.throughput_kpi_tree.unidades": "unidades/{time_unit}",
    "kpi.kpi.throughput_kpi_tree.utilizacion": "Utilización",
    "main.cli.add_lam_mu.tasa_llegadas": "Tasa de llegadas λ",
    "main.cli.add_lam_mu.tasa_servicio_servidor": "Tasa de servicio μ por servidor",
    "main.cli.main.aproximacion_kingman": "Aproximación de Kingman para G/G/1",
    "main.cli.main.cantidad_economica_pedido_eoq": "Cantidad económica de pedido (EOQ)",
    "main.cli.main.cola_servicio_deterministico": "Cola M/D/1 con servicio determinístico",
    "main.cli.main.cola_servidor": "Cola M/M/1 de un servidor",
    "main.cli.main.cola_varios_servidores": "Cola M/M/c de varios servidores",
    "main.cli.main.costo_fijo_pedido": "Costo fijo por pedido",
    "main.cli.main.costo_mantener_unidad_periodo": "Costo de mantener por unidad y periodo",
    "main.cli.main.cv2_tiempos_entre_llegadas": "CV² de los tiempos entre llegadas",
    "main.cli.main.cv2_tiempos_servicio": "CV² de los tiempos de servicio",
    "main.cli.main.error": "Error: {exc}",
    "main.cli.main.herramientas_teoria_colas_investigacion_operaciones": "Herramientas de teoría de colas e investigación de operaciones.",
    "main.cli.main.modelo": "MODELO",
    "main.cli.main.numero_servidores": "Número de servidores",
    "main.cli.main.resuelve_ley_little_variable_faltante": "Resuelve la ley de Little para la variable faltante",
    "main.cli.main.tasa_demanda_unidades_periodo": "Tasa de demanda (unidades/periodo)",
    "main.cli.main.walopy": "walopy {__version__}",
    "network.cabecera.to_frame.estacion": "Estación",
    "network.cabecera.to_frame.ext": "λ_ext",
    "network.cabecera.to_frame.total": "λ_total",
    "network.clave_params.jackson_network.texto": "J",
    "network.clave_params.jackson_network.total_gamma": "total_gamma",
    "network.error.jackson_network.estacion_inestable_aumente_capacidad_reduzca": "La estación '{expr}' es inestable: ρ = {rho_j:.4g} ≥ 1. Aumente la capacidad o reduzca las tasas de llegada.",
    "network.error.jackson_network.filas_matriz_ruteo_deben_sumar": "Las filas de la matriz de ruteo deben sumar ≤ 1.",
    "network.error.jackson_network.mu_gamma_station_names_deben": "'mu', 'gamma' y 'station_names' deben tener la misma longitud.",
    "network.error.jackson_network.routing_debe_ser_matriz_recibio": "'routing' debe ser una matriz ({J}×{J2}), se recibió forma {shape}.",
    "network.error.jackson_network.servers_debe_tener_misma_longitud": "'servers' debe tener la misma longitud que 'station_names'.",
    "network.error.jackson_network.tasas_llegada_efectivas_negativas_revise": "Tasas de llegada efectivas negativas: revise la matriz de ruteo (¿lazos cerrados?).",
    "network.error.jackson_network.todas_probabilidades_ruteo_deben_ser": "Todas las probabilidades de ruteo deben ser ≥ 0.",
    "network.etiqueta.summary.sistema_clientes_totales_red": "L_sistema : {L_system:.6g}  (clientes totales en la red)",
    "network.etiqueta.summary.sistema_tiempo_medio_permanencia_red": "W_sistema : {W_system:.6g}  (tiempo medio de permanencia en la red)",
    "network.texto_en_expresion.summary.estacion": "Estación",
    "network.texto_en_expresion.summary.ext": "λ_ext",
    "network.texto_en_expresion.summary.lq": "Lq",
    "network.texto_en_expresion.summary.texto": "L",
    "network.texto_en_expresion.summary.texto_2": "W",
    "network.texto_en_expresion.summary.tot": "λ_tot",
    "network.texto_en_expresion.summary.wq": "Wq",
    "operations.cabecera.to_frame.calidad": "Calidad (Q)",
    "operations.cabecera.to_frame.capacidad": "Capacidad",
    "operations.cabecera.to_frame.costo_fijo_unidad": "Costo fijo / unidad",
    "operations.cabecera.to_frame.costo_total": "Costo total",
    "operations.cabecera.to_frame.costo_unitario_total": "Costo unitario total",
    "operations.cabecera.to_frame.costo_variable_unidad": "Costo variable / unidad",
    "operations.cabecera.to_frame.disponibilidad": "Disponibilidad (A)",
    "operations.cabecera.to_frame.eficiencia": "Eficiencia",
    "operations.cabecera.to_frame.rendimiento": "Rendimiento (P)",
    "operations.cabecera.to_frame.throughput": "Throughput",
    "operations.cabecera.to_frame.unidades_producidas": "Unidades producidas",
    "operations.cabecera.to_frame.utilizacion": "Utilización",
    "operations.etiqueta.summary.calidad": "Calidad        (Q) : {quality:.2%}",
    "operations.etiqueta.summary.disponibilidad": "Disponibilidad (A) : {availability:.2%}",
    "operations.etiqueta.summary.oee": "OEE                : {oee:.2%}",
    "operations.etiqueta.summary.rendimiento": "Rendimiento    (P) : {performance:.2%}",
    "operations.etiqueta.summary.unidades_producidas_costo_fijo_unidad": "Unidades producidas    : {units_produced:.6g}\nCosto fijo / unidad    : {fixed_cost_per_unit:.6g}\nCosto variable / unidad: {variable_cost_per_unit:.6g}\nCosto unitario total   : {unit_cost:.6g}\nCosto total            : {total_cost:.6g}",
    "operations.etiqueta.summary.utilizacion_eficiencia_throughput_capacidad": "Utilización : {utilization:.2%}\nEficiencia  : {efficiency:.2%}\nThroughput  : {throughput:.6g}\nCapacidad   : {capacity:.6g}",
    "plotting.grafica.collect.br": "<b>{name}</b><br>{value:.6g}{unit_str}{formula_str}",
    "plotting.grafica.collect.br_2": "<br><i>{formula}</i>",
    "plotting.grafica.plot_bottleneck.cuello_botella": "Cuello de botella: {bottleneck}",
    "plotting.grafica.plot_bottleneck.limite_capacidad": "Límite de capacidad",
    "plotting.grafica.plot_bottleneck.utilizacion": "Utilización",
    "plotting.grafica.plot_break_even.analisis_punto_equilibrio": "Análisis de punto de equilibrio",
    "plotting.grafica.plot_break_even.ingresos": "Ingresos",
    "plotting.grafica.plot_break_even.monto": "Monto",
    "plotting.grafica.plot_break_even.pe": "PE ({bep:.0f} {expr})",
    "plotting.grafica.plot_break_even.punto_equilibrio": "Punto de equilibrio",
    "plotting.grafica.plot_break_even.real": "Real ({actual:.0f})",
    "plotting.grafica.plot_break_even.unidades": "Unidades",
    "plotting.grafica.plot_break_even.ventas": "Ventas",
    "plotting.grafica.plot_break_even.zona_utilidad": "Zona de utilidad",
    "plotting.grafica.plot_eoq.cantidad_pedido": "Cantidad de pedido Q",
    "plotting.grafica.plot_eoq.costo_mantener_hq": "Costo de mantener (hQ/2)",
    "plotting.grafica.plot_eoq.costo_ordenar_kd": "Costo de ordenar (KD/Q)",
    "plotting.grafica.plot_eoq.eoq": "EOQ = {Q_star:.4g}",
    "plotting.grafica.plot_eoq.eoq_curvas_costo": "EOQ — Curvas de costo",
    "plotting.grafica.plot_kpi_tree.arbol_kpi": "Árbol de KPI — {name}",
    "plotting.grafica.plot_kpi_tree.customdata_extra_extra": "%{{customdata}}<extra></extra>",
    "plotting.grafica.plot_line_balance.balance_linea_efic": "Balance de línea — efic. {balance_efficiency:.1%}",
    "plotting.grafica.plot_line_balance.estacion": "Estación",
    "plotting.grafica.plot_line_balance.takt": "Takt = {takt:.4g}",
    "plotting.grafica.plot_line_balance.tiempo": "Tiempo",
    "plotting.grafica.plot_line_balance.tiempo_ciclo": "Tiempo de ciclo",
    "plotting.grafica.plot_line_balance.tiempo_ocioso": "Tiempo ocioso",
    "plotting.grafica.plot_oee.calidad": "Calidad",
    "plotting.grafica.plot_oee.clase_mundial_85": "Clase mundial (85%)",
    "plotting.grafica.plot_oee.descomposicion_oee": "Descomposición del OEE",
    "plotting.grafica.plot_oee.disponibilidad": "Disponibilidad",
    "plotting.grafica.plot_oee.rendimiento": "Rendimiento",
    "plotting.grafica.plot_oee.valor_factor": "Valor del factor",
    "plotting.grafica.plot_optimize_servers.costo_espera": "Costo de espera",
    "plotting.grafica.plot_optimize_servers.costo_servidores": "Costo de servidores",
    "plotting.grafica.plot_optimize_servers.costo_total": "Costo total",
    "plotting.grafica.plot_optimize_servers.costo_unidad_tiempo": "Costo por unidad de tiempo",
    "plotting.grafica.plot_optimize_servers.numero_servidores": "Número de servidores (c)",
    "plotting.grafica.plot_optimize_servers.optimizacion_costo_servidores": "Optimización del costo de servidores",
    "plotting.grafica.plot_optimize_servers.optimo": "c óptimo = {optimal_servers}",
    "plotting.grafica.plot_queue_distribution.clientes": "n (clientes)",
    "plotting.grafica.plot_queue_distribution.distribuciones": "Distribuciones M/M/1",
    "plotting.grafica.plot_queue_distribution.fda_tiempo_permanencia": "F(t) — FDA del tiempo de permanencia",
    "plotting.grafica.plot_queue_distribution.longitud_cola": "P(N = n) — Longitud de la cola",
    "plotting.grafica.plot_queue_distribution.nn": "P(N≤n)",
    "plotting.grafica.plot_queue_distribution.probabilidad": "Probabilidad",
    "plotting.grafica.plot_queue_distribution.texto": "F(t)",
    "plotting.grafica.plot_queue_distribution.texto_2": "F(t) / f(t)",
    "plotting.grafica.plot_queue_distribution.texto_3": "P(N=n)",
    "plotting.grafica.plot_queue_distribution.texto_4": "f(t)",
    "plotting.grafica.plot_queue_distribution.tiempo": "t (tiempo)",
    "plotting.grafica.plot_queue_metrics.resumen_kpi": "{model} — Resumen de KPI",
    "plotting.grafica.plot_queue_metrics.valor": "Valor",
    "plotting.grafica.plot_queue_sensitivity.curva": "curva de {label}",
    "plotting.grafica.plot_queue_sensitivity.lq_longitud_media_cola": "Lq (longitud media de cola)",
    "plotting.grafica.plot_queue_sensitivity.sensibilidad_cola": "{model} — Sensibilidad de la cola",
    "plotting.grafica.plot_queue_sensitivity.utilizacion": "Utilización ρ",
    "plotting.grafica.plot_queue_sensitivity.wq_espera_media_cola": "Wq (espera media en cola)",
    "plotting.grafica.plot_sensitivity.sensibilidad": "Sensibilidad: {param}",
    "plotting.grafica.plot_simulation.distribucion_wq": "Distribución de Wq",
    "plotting.grafica.plot_simulation.fda_empirica": "FDA empírica",
    "plotting.grafica.plot_simulation.fda_wq": "FDA de Wq",
    "plotting.grafica.plot_simulation.frecuencia": "Frecuencia",
    "plotting.grafica.plot_simulation.probabilidad_acumulada": "Probabilidad acumulada",
    "plotting.grafica.plot_simulation.wq": "Wq",
    "plotting.grafica.plot_simulation.wq_tiempo_espera": "Wq (tiempo de espera)",
    "plotting.texto_en_expresion.plot_break_even.unidades": "unidades",
    "plotting.texto_en_expresion.plot_break_even.ventas": "ventas",
    "project.cabecera.to_frame.actividad": "Actividad",
    "project.cabecera.to_frame.critica": "Crítica",
    "project.cabecera.to_frame.duracion": "Duración",
    "project.cabecera.to_frame.hl": "HL",
    "project.cabecera.to_frame.ht": "HT",
    "project.cabecera.to_frame.predecesoras": "Predecesoras",
    "project.error.cpm.actividad_falta_clave_duration": "Actividad '{nm}': falta la clave 'duration'.",
    "project.error.leer_actividades.activities_debe_contener_menos_actividad": "'activities' debe contener al menos una actividad.",
    "project.error.leer_actividades.activities_debe_ser_diccionario_recibio": "activities[{i}] debe ser un diccionario, se recibió {__name__!r}.",
    "project.error.leer_actividades.activities_debe_ser_lista_diccionarios": "'activities' debe ser una lista de diccionarios.",
    "project.error.leer_actividades.activities_falta_clave_name": "activities[{i}]: falta la clave 'name'.",
    "project.error.leer_actividades.activities_predecessors_debe_ser_lista": "activities[{i}]['predecessors'] debe ser una lista de nombres.",
    "project.error.leer_actividades.nombre_actividad_duplicado_cada_actividad": "Nombre de actividad duplicado: '{nm}'. Cada actividad debe tener un nombre único.",
    "project.error.pert.actividad_falta_clave": "Actividad '{nm}': falta la clave '{clave}'.",
    "project.error.pert.actividad_requiere_optimistic_most_likely": "Actividad '{nm}': se requiere optimistic ≤ most_likely ≤ pessimistic.",
    "project.error.probability.probability_requiere_resultado_pert_varianza": "probability() requiere un resultado PERT con varianza distinta de cero.",
    "project.error.toposort_and_succ.actividad_referencia_predecesor_desconocido": "La actividad '{name}' referencia un predecesor desconocido '{pred}'.",
    "project.error.toposort_and_succ.actividades_contienen_ciclo": "Las actividades contienen un ciclo.",
    "project.etiqueta.summary.duracion_proyecto": "Duración proyecto  : {project_duration:.4g}",
    "project.etiqueta.summary.metodo": "Método            : {method}",
    "project.etiqueta.summary.proyecto": "σ del proyecto     : {project_std:.4g}",
    "project.etiqueta.summary.ruta_critica": "Ruta crítica       : {expr}",
    "project.etiqueta.summary.varianza_proyecto": "Varianza proyecto  : {project_variance:.4g}",
    "queuing.cabecera.to_frame.lq_cola": "Lq (en cola)",
    "queuing.cabecera.to_frame.servidores": "c (servidores)",
    "queuing.cabecera.to_frame.sistema": "L (en el sistema)",
    "queuing.cabecera.to_frame.tasa_llegada": "λ (tasa de llegada)",
    "queuing.cabecera.to_frame.tasa_servicio": "μ (tasa de servicio)",
    "queuing.cabecera.to_frame.tiempo_sistema": "W (tiempo en el sistema)",
    "queuing.cabecera.to_frame.utilizacion": "ρ (utilización)",
    "queuing.cabecera.to_frame.wq_tiempo_espera": "Wq (tiempo de espera)",
    "queuing.clave_params.kingman.ca2_cv2_llegadas": "ca² (CV² de llegadas)",
    "queuing.clave_params.kingman.cs2_cv2_servicio": "cs² (CV² de servicio)",
    "queuing.clave_params.mm1.p0_prob_sistema_vacio": "P0 (prob. de sistema vacío)",
    "queuing.clave_params.mmc.erlang": "C(c,a) Erlang-C",
    "queuing.error.cv2_triangular.media_distribucion_cv2_esta_definido": "La media de la distribución es 0: CV² no está definido.",
    "queuing.error.cv2_triangular.triangular_requiere": "La triangular requiere a ≤ m ≤ b.",
    "queuing.error.cv2_uniform.uniforme_requiere": "La uniforme requiere b > a.",
    "queuing.error.littles_law.exactamente_lam_debe_ser_none": "Exactamente una de L, lam, W debe ser None.",
    "queuing.error.md1.sistema_inestable": "Sistema inestable: ρ = {rho:.4g} ≥ 1.",
    "queuing.error.mm1.sistema_inestable_requiere": "Sistema inestable: ρ = {rho:.4g} ≥ 1. Se requiere λ < μ.",
    "queuing.error.mmc.sistema_inestable_requiere": "Sistema inestable: ρ = {rho:.4g} ≥ 1. Se requiere λ < c·μ.",
    "queuing.etiqueta.summary.lq_unidades_promedio_cola": "Lq     : {Lq:.6g}  (unidades promedio en cola)",
    "queuing.etiqueta.summary.modelo": "Modelo : {model}",
    "queuing.etiqueta.summary.servidores": "c      : {servers}  (servidores)",
    "queuing.etiqueta.summary.tasa_llegada": "λ      : {lam:.6g}  (tasa de llegada)",
    "queuing.etiqueta.summary.tasa_servicio_servidor": "μ      : {mu:.6g}  (tasa de servicio por servidor)",
    "queuing.etiqueta.summary.tiempo_promedio_sistema": "W      : {W:.6g}  (tiempo promedio en el sistema)",
    "queuing.etiqueta.summary.unidades_promedio_sistema": "L      : {L:.6g}  (unidades promedio en el sistema)",
    "queuing.etiqueta.summary.utilizacion_servidor": "ρ      : {rho:.6g}  (utilización por servidor)",
    "queuing.etiqueta.summary.wq_tiempo_promedio_espera_cola": "Wq     : {Wq:.6g}  (tiempo promedio de espera en cola)",
    "queuing.modelo.kingman.kingman": "G/G/1 (Kingman)",
    "queuing.modelo.mmc.texto": "M/M/{c}",
    "reliability.aviso.weibull_mle_beta.forma_estimada_menor_igual_cota": "La forma β estimada es menor o igual que la cota inferior {lo:g}; el resultado es el límite del intervalo de búsqueda, no un máximo de verosimilitud exacto.",
    "reliability.aviso.weibull_mle_beta.tiempos_falla_casi_tienen_dispersion": "Los tiempos de falla casi no tienen dispersión: la forma β supera la cota {hi:g}; el resultado es el límite del intervalo de búsqueda, no el estimador exacto.",
    "reliability.cabecera.to_frame.componentes": "Componentes",
    "reliability.cabecera.to_frame.disponibilidad": "Disponibilidad",
    "reliability.cabecera.to_frame.escala": "η (escala)",
    "reliability.cabecera.to_frame.forma": "β (forma)",
    "reliability.cabecera.to_frame.metodo": "método",
    "reliability.cabecera.to_frame.texto": "R(t={t})",
    "reliability.cabecera.to_frame.topologia": "Topología",
    "reliability.clave_params.koon_system.texto": "k",
    "reliability.error.b_life.pct_debe_estar_estrictamente_entre": "'pct' debe estar estrictamente entre 0 y 100.",
    "reliability.error.koon_system.debe_cumplirse": "Debe cumplirse 1 ≤ k ≤ n (k={k}, n={n}).",
    "reliability.error.r_system.topologia_desconocida": "Topología desconocida: {topology!r}",
    "reliability.error.weibull_analysis.method_debe_ser_mle_rry": "'method' debe ser 'MLE' o 'RRY'.",
    "reliability.error.weibull_analysis.todos_tiempos_falla_son_iguales": "Todos los tiempos de falla son iguales: la dispersión es nula y la forma β no es estimable.",
    "reliability.etiqueta.summary.componentes": "Componentes     : {n_components}",
    "reliability.etiqueta.summary.disponibilidad": "Disponibilidad  : {availability:.4%}",
    "reliability.etiqueta.summary.metodo_forma_escala_mttf_vida": "Método       : {method} (n={n})\nForma β      : {shape:.4f}\nEscala η     : {scale:.4g}\nMTTF         : {mttf:.4g}\nVida B10     : {b10:.4g}\nB50 (mediana): {b50:.4g}",
    "reliability.etiqueta.summary.mtbf": "MTBF            : {mtbf:.6g}",
    "reliability.etiqueta.summary.tasas_falla": "Tasas de falla λ: {expr}",
    "reliability.etiqueta.summary.texto": "R(t={t:.4g})       : {R_t:.6g}",
    "reliability.etiqueta.summary.topologia": "Topología       : {topology}",
    "scheduling.cabecera.to_frame.fin": "M{expr}_fin",
    "scheduling.cabecera.to_frame.inicio": "M{expr}_inicio",
    "scheduling.cabecera.to_frame.inicio_2": "Inicio",
    "scheduling.cabecera.to_frame.m1_fin": "M1 fin",
    "scheduling.cabecera.to_frame.m1_inicio": "M1 inicio",
    "scheduling.cabecera.to_frame.m2_fin": "M2 fin",
    "scheduling.cabecera.to_frame.m2_inicio": "M2 inicio",
    "scheduling.cabecera.to_frame.retraso": "Con retraso",
    "scheduling.cabecera.to_frame.trabajo": "Trabajo",
    "scheduling.error.johnson_flowshop.m1_times_m2_times_deben": "m1_times y m2_times deben tener la misma longitud.",
    "scheduling.error.neh_flowshop.cada_trabajo_debe_tener_tiempos": "Cada trabajo debe tener tiempos de proceso para al menos una máquina.",
    "scheduling.error.neh_flowshop.names_debe_tener_misma_longitud": "'names' debe tener la misma longitud que 'times_matrix'.",
    "scheduling.error.neh_flowshop.times_matrix_debe_contener_menos": "'times_matrix' debe contener al menos un trabajo.",
    "scheduling.error.neh_flowshop.todas_filas_deben_tener_misma": "Todas las filas deben tener la misma longitud; la fila {i} tiene {expr} ≠ {m_cnt}.",
    "scheduling.error.schedule_single.rule_debe_ser": "'rule' debe ser una de {valid}.",
    "scheduling.error.schedule_single.rule_requiere_due_dates": "rule='{rule}' requiere due_dates.",
    "scheduling.error.schedule_single.todas_secuencias_entrada_deben_tener": "Todas las secuencias de entrada deben tener la misma longitud.",
    "scheduling.etiqueta.summary.algoritmo_heuristica_neh_maquinas_secuencia": "Algoritmo : heurística NEH\nMáquinas  : {n_machines}\nSecuencia : {expr}\nMakespan  : {makespan:.4g}",
    "scheduling.etiqueta.summary.finalizacion_pond_wcj": "Finalización pond. ΣwCj : {total_weighted_completion_time:.4g}",
    "scheduling.etiqueta.summary.finalizacion_total_cj": "Finalización total ΣCj  : {total_completion_time:.4g}",
    "scheduling.etiqueta.summary.makespan_cmax": "Makespan (Cmax)         : {makespan:.4g}",
    "scheduling.etiqueta.summary.regla": "Regla                   : {rule}",
    "scheduling.etiqueta.summary.retraso_maximo": "Retraso máximo          : {max_lateness:.4g}",
    "scheduling.etiqueta.summary.secuencia": "Secuencia               : {expr}",
    "scheduling.etiqueta.summary.secuencia_makespan": "Secuencia : {expr}\nMakespan  : {makespan:.4g}",
    "scheduling.etiqueta.summary.tardanza_total_tj": "Tardanza total ΣTj      : {total_tardiness:.4g}",
    "scheduling.etiqueta.summary.trabajos_retraso": "Trabajos con retraso    : {n_tardy}",
    "scheduling.valor_por_defecto.schedule_single.texto": "J{expr}",
    "solver.clave_params.optimize_servers.cost_per_server": "cost_per_server",
    "solver.clave_params.optimize_servers.cost_per_wait": "cost_per_wait",
    "solver.clave_params.solve_lam.model": "model",
    "solver.clave_params.solve_lam.mu": "mu",
    "solver.clave_params.solve_mu.lam": "lam",
    "solver.error.batch_model.errors_debe_ser_collect_raise": "'errors' debe ser 'collect' o 'raise'.",
    "solver.error.bisect.raiz_esta_acotada_objetivo_puede": "La raíz no está acotada: f({a:.6g})={fa:.4g}, f({b:.6g})={fb:.4g}. El objetivo puede estar fuera del rango factible.",
    "solver.error.get_metric.metrica_desconocida_opciones_validas": "Métrica desconocida '{metric}'. Opciones válidas: {valid}",
    "solver.error.solve_lam.modelo_desconocido_elija_entre": "Modelo desconocido '{model}'. Elija entre {expr}.",
    "solver.error.solve_lam.supera_incluso_muy_baja_objetivo": "{target_metric} supera {target_value} incluso con λ muy baja. El objetivo puede ser infactible para este modelo / μ.",
    "solver.error.solve_mu.sigue_superando_objetivo_puede_ser": "{target_metric} sigue superando {target_value} con μ = {mu_max:.4g}. El objetivo puede ser numéricamente infactible.",
    "solver.error.solve_servers.pudo_cumplir_hasta_servidores_considere": "No se pudo cumplir {target_metric} ≤ {target_value} con hasta {c_max} servidores. Considere aumentar μ o relajar el objetivo.",
    "solver.error.optimize_servers.sin_servidores_estables_hasta_c_max": "Con λ={lam} y μ={mu} hacen falta al menos {c_min} servidores para que el sistema sea estable, pero c_max={c_max}. Aumente c_max.",
    "solver.error.sensitivity.values_no_puede_estar_vacio": "values no puede estar vacío.",
    "solver.error.sensitivity.param_no_es_parametro_modelo": "{param!r} no es un parámetro de {modelo}.",
    "solver.error.compare.sin_resultados": "compare necesita al menos un resultado.",
    "solver.etiqueta.compare.escenario": "escenario_{expr}",
    "solver.etiqueta.summary.convergio": "NO convergió",
    "solver.etiqueta.summary.convergio_2": "convergió",
    "solver.etiqueta.summary.servidores_optimos_costo_minimo_unidad": "Servidores óptimos : {optimal_servers}\nCosto mínimo       : {min_cost:.6g} por unidad de tiempo\n",
    "solver.etiqueta.summary.solver_parametro_resuelto_metrica_objetivo": "Solver [{status}]\n  Parámetro resuelto : {param} = {value:.6g}\n  Métrica objetivo   : {target_metric} ≤ {target_value:.6g}\n  Logrado            : {target_metric2} = {achieved_value:.6g}",
    "utils.error.as_finite_scalar.debe_ser_numero_finito_recibio": "'{name}' debe ser un número finito, se recibió {value!r}.",
    "utils.error.as_float_list.debe_contener_menos_elementos_recibieron": "'{name}' debe contener al menos {min_len} elementos, se recibieron {expr}.",
    "utils.error.as_float_list.debe_ser_secuencia_numeros_recibio": "'{name}' debe ser una secuencia de números, se recibió {__name__!r}.",
    "utils.error.as_fraction.debe_ser_valor_finito_recibio": "'{name}' debe ser un valor finito en [0, 1], se recibió {value!r}.",
    "utils.error.as_int_positive.debe_ser_entero_positivo_recibio": "'{name}' debe ser un entero positivo, se recibió {__name__!r} = {value!r}.",
    "utils.error.as_int_positive.debe_ser_recibio": "'{name}' debe ser >= 1, se recibió {value!r}.",
    "utils.error.as_int_positive.puede_superar_recibio": "'{name}' no puede superar {max}, se recibió {value!r}.",
    "utils.error.as_nonempty.debe_contener_menos_elemento": "'{name}' debe contener al menos un elemento.",
    "utils.error.as_nonneg.debe_ser_finito_recibio": "'{name}' debe ser finito y >= 0, se recibió {value!r}.",
    "utils.error.as_positive.debe_ser_numero_finito_positivo": "'{name}' debe ser un número finito y positivo, se recibió {value!r}.",
    "utils.error.to_float.debe_ser_numero_recibio": "'{name}' debe ser un número, se recibió {__name__!r}.",
    "utils.error.to_float.debe_ser_numero_recibio_booleano": "'{name}' debe ser un número, se recibió un booleano ({value!r}).",
}
